// Engine/EngineClasses.h: the Engine package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_ENGINE_ENGINECLASSES_H
#define T3_ENGINE_ENGINECLASSES_H

#include "Core/Core.h"
#include "Core/CoreClasses.h"

class AActor;
class AController;
class AEmitter;
class AInterpolationPoint;
class ALevelInfo;
class ANavigationPoint;
class APawn;
class APhysicsVolume;
class APlayerController;
class ASkyZoneInfo;
class ATerrainInfo;
class AZoneInfo;
class UAISubsystem;
class UClient;
class UFont;
class UGameSubsystem;
class UIndexBuffer;
class ULevel;
class UMatAction;
class UMatSubAction;
class UMesh;
class UPalette;
class UParticleEmitter;
class UPhysicsSubsystem;
class UPlayer;
class UPrimitive;
class URenderDevice;
class UStaticMesh;
class UTerrainPrimitive;
class UTerrainSector;
class UTexture;
class UVertexBuffer;
class UViewport;

enum EAffect
{
    AFFECT_ViewportCamera,
    AFFECT_Actor
};

enum EBeamEndPointType
{
    PTEP_Velocity,
    PTEP_Distance,
    PTEP_Offset,
    PTEP_Actor,
    PTEP_TraceOffset
};

enum ECsgOper
{
    CSG_Active,
    CSG_Add,
    CSG_Subtract,
    CSG_Intersect,
    CSG_Deintersect
};

enum EDoubleClickDir
{
    DCLICK_None,
    DCLICK_Left,
    DCLICK_Right,
    DCLICK_Forward,
    DCLICK_Back,
    DCLICK_Active,
    DCLICK_Done
};

enum EEnvMapTransformType
{
    EMTT_ViewSpace,
    EMTT_WorldSpace,
    EMTT_LightSpace
};

enum EForceType
{
    FT_None,
    FT_DragAlong
};

enum eGoalState
{
    kGS_Pending,
    kGS_Success,
    kGS_Failed,
    kGS_Cancelled,
    kGS_Hidden
};

enum eGoalType
{
    kGT_Objective,
    kGT_Restriction,
    kGT_Note
};

enum ELevelAction
{
    LEVACT_None,
    LEVACT_Loading,
    LEVACT_Saving,
    LEVACT_Connecting,
    LEVACT_Precaching
};

enum ELODSet
{
    LODSET_None,
    LODSET_World,
    LODSET_Skin
};

enum eLootType
{
    eLT_METAL,
    eLT_ART,
    eLT_GEM,
    eLT_SPECIAL
};

enum ENetMode
{
    NM_Standalone,
    NM_DedicatedServer,
    NM_ListenServer,
    NM_Client
};

enum ENetRole
{
    ROLE_None,
    ROLE_DumbProxy,
    ROLE_SimulatedProxy,
    ROLE_AutonomousProxy,
    ROLE_Authority
};

enum EParticleCoordinateSystem
{
    PTCS_Independent,
    PTCS_Relative,
    PTCS_Absolute
};

enum EParticleDirectionUsage
{
    PTDU_None,
    PTDU_Up,
    PTDU_Right,
    PTDU_Forward,
    PTDU_Normal,
    PTDU_UpAndNormal,
    PTDU_RightAndNormal,
    PTDU_Oriented
};

enum EParticleDrawStyle
{
    PTDS_Regular,
    PTDS_AlphaBlend,
    PTDS_Modulated,
    PTDS_Translucent,
    PTDS_AlphaModulate,
    PTDS_Darken,
    PTDS_Brighten,
    PTDS_TextureAndVertexAlphaBlend,
    PTDS_MultiplyColorByAlphaThenAddToFrameBuffer
};

enum EParticleEffectAxis
{
    PTEA_NegativeX,
    PTEA_PositiveZ
};

enum EParticleRotationSource
{
    PTRS_None,
    PTRS_Actor,
    PTRS_Offset,
    PTRS_Normal,
    PTRS_Bone
};

enum EParticleStartLocationShape
{
    PTLS_Box,
    PTLS_Sphere
};

enum EParticleTrailingLifetime
{
    kPTL_Independent,
    kPTL_Percentage
};

enum EParticleVelocityDirection
{
    PTVD_None,
    PTVD_StartPositionAndOwner,
    PTVD_OwnerAndStartPosition
};

enum EPathStyle
{
    PATHSTYLE_Linear,
    PATHSTYLE_Bezier
};

enum ESAStatus
{
    SASTATUS_Waiting,
    SASTATUS_Running,
    SASTATUS_Ending,
    SASTATUS_Expired
};

enum ETexClampMode
{
    TC_Wrap,
    TC_Clamp
};

enum ETexMapAxis
{
    TEXMAPAXIS_XY,
    TEXMAPAXIS_XZ,
    TEXMAPAXIS_YZ
};

enum ETextureFormat
{
    TEXF_P8,
    TEXF_RGBA7,
    TEXF_RGB16,
    TEXF_DXT1,
    TEXF_RGB8,
    TEXF_RGBA8,
    TEXF_NODATA,
    TEXF_DXT3,
    TEXF_DXT5,
    TEXF_G8,
    TEXF_G16
};

struct FPointRegion
{
    AZoneInfo* Zone;                        // 0x0
    INT iLeaf;                              // 0x4
    BYTE ZoneNumberLow;                     // 0x8
    BYTE ZoneNumberHigh;                    // 0x9
    BYTE PadA[0x2];
};
T3_CHECK_SIZE(FPointRegion, 0xC);

struct FsGoal
{
    FName GoalName;                         // 0x0
    FStringNoInit FriendlyName;             // 0x4
    FStringNoInit GoalText;                 // 0x10
    BYTE GoalState;                         // 0x1C  eGoalState
    BITFIELD bPrimary:1;                    // 0x20
    BYTE GoalType;                          // 0x24  eGoalType
    BITFIELD bHasParent:1;                  // 0x28
    FName GoalParent;                       // 0x2C
};
T3_CHECK_SIZE(FsGoal, 0x30);

struct FsCitySectionGoal
{
    FName CitySectionName;                  // 0x0
    FsGoal goal;                            // 0x4
};
T3_CHECK_SIZE(FsCitySectionGoal, 0x34);

struct FsNote
{
    FName NoteName;                         // 0x0
    FStringNoInit FriendlyName;             // 0x4
    FStringNoInit NoteText;                 // 0x10
    INT Expiration;                         // 0x1C
};
T3_CHECK_SIZE(FsNote, 0x20);

struct FLightLevelInfo
{
    FVector LightLevel;                     // 0x0
    INT WeightClass;                        // 0xC
};
T3_CHECK_SIZE(FLightLevelInfo, 0x10);

struct FsLightLevelDebugInfo
{
    FVector CalculatedLightLevel;           // 0x0
    FLOAT CalculatedRawVisibility;          // 0xC
    FLOAT RawVisibilityWithModifiers;       // 0x10
    FLOAT TargetVisibility;                 // 0x14
    FLOAT CurrentVisibilty;                 // 0x18
};
T3_CHECK_SIZE(FsLightLevelDebugInfo, 0x1C);

struct FOrientation
{
    BYTE CamOrientation;                    // 0x0  ECamOrientation
    AActor* LookAt;                         // 0x4
    FLOAT EaseIntime;                       // 0x8
    INT bReversePitch;                      // 0xC
    INT bReverseYaw;                        // 0x10
    INT bReverseRoll;                       // 0x14
    INT MA;                                 // 0x18
    FLOAT PctInStart;                       // 0x1C
    FLOAT PctInEnd;                         // 0x20
    FLOAT PctInDuration;                    // 0x24
    FRotator StartingRotation;              // 0x28
};
T3_CHECK_SIZE(FOrientation, 0x34);

struct FTerrainLayer
{
    UTexture* Texture;                      // 0x0
    UTexture* AlphaMap;                     // 0x4
    FLOAT UScale;                           // 0x8
    FLOAT VScale;                           // 0xC
    FLOAT UPan;                             // 0x10
    FLOAT VPan;                             // 0x14
    BYTE TextureMapAxis;                    // 0x18  ETexMapAxis
    FLOAT TextureRotation;                  // 0x1C
    FRotator LayerRotation;                 // 0x20
};
T3_CHECK_SIZE(FTerrainLayer, 0x2C);

struct FDecorationLayer
{
    BITFIELD ShowOnTerrain:1;               // 0x0
    UTexture* ScaleMap;                     // 0x4
    UTexture* DensityMap;                   // 0x8
    UTexture* ColorMap;                     // 0xC
    UStaticMesh* StaticMesh;                // 0x10
    FVector ScaleMultiplier;                // 0x14
    FRange FadeoutRadius;                   // 0x20
    FRange DensityMultiplier;               // 0x28
    INT MaxPerQuad;                         // 0x30
    INT Seed;                               // 0x34
    INT AlignToTerrain;                     // 0x38
    BYTE DrawOrder;                         // 0x3C
    INT ShowOnInvisibleTerrain;             // 0x40
};
T3_CHECK_SIZE(FDecorationLayer, 0x44);

struct FNormalPair
{
    FVector Normal1;                        // 0x0
    FVector Normal2;                        // 0xC
};
T3_CHECK_SIZE(FNormalPair, 0x18);

struct FParticleColorScale
{
    FLOAT RelativeTime;                     // 0x0
    FColor Color;                           // 0x4
};
T3_CHECK_SIZE(FParticleColorScale, 0x8);

struct FParticleTimeScale
{
    FLOAT RelativeTime;                     // 0x0
    FLOAT RelativeSize;                     // 0x4
};
T3_CHECK_SIZE(FParticleTimeScale, 0x8);

struct FParticle
{
    FVector Location;                       // 0x0
    FVector Velocity;                       // 0xC
    BYTE Mass;                              // 0x18
    BYTE StartSize;                         // 0x19
    BYTE SpinsPerSecond;                    // 0x1A
    BYTE StartSpin;                         // 0x1B
    BYTE HitCount;                          // 0x1C
    BYTE HitUpdateTime;                     // 0x1D
    BYTE Flags;                             // 0x1E
    BYTE Subdivision;                       // 0x1F
    FLOAT Time;                             // 0x20
    FLOAT MaxLifetime;                      // 0x24
};
T3_CHECK_SIZE(FParticle, 0x28);

struct FParticleBeamEndPoint
{
    FName ActorTag;                         // 0x0
    FRangeVector Offset;                    // 0x4
    FLOAT Weight;                           // 0x1C
};
T3_CHECK_SIZE(FParticleBeamEndPoint, 0x20);

struct FParticleBeamScale
{
    FVector FrequencyScale;                 // 0x0
    FLOAT RelativeLength;                   // 0xC
};
T3_CHECK_SIZE(FParticleBeamScale, 0x10);

struct FParticleBeamData
{
    FVector Location;                       // 0x0
    FLOAT t;                                // 0xC
    FLOAT Alpha;                            // 0x10
};
T3_CHECK_SIZE(FParticleBeamData, 0x14);

struct FURL
{
    FStringNoInit Protocol;                 // 0x0
    FStringNoInit Host;                     // 0xC
    INT Port;                               // 0x18
    FStringNoInit Map;                      // 0x1C
    TArray<FString> Op;                     // 0x28
    FStringNoInit Portal;                   // 0x34
    BITFIELD Valid:1;                       // 0x40
};
T3_CHECK_SIZE(FURL, 0x44);

struct FParticleSparkData
{
    FLOAT TimeBeforeVisible;                // 0x0
    FLOAT TimeBetweenSegments;              // 0x4
    FVector StartLocation;                  // 0x8
    FVector StartVelocity;                  // 0x14
};
T3_CHECK_SIZE(FParticleSparkData, 0x20);

struct FMatObjectOrientation
{
    BYTE CamOrientation;                    // 0x0  ECamOrientation
    AActor* LookAt;                         // 0x4
    FLOAT EaseIntime;                       // 0x8
    INT bReversePitch;                      // 0xC
    INT bReverseYaw;                        // 0x10
    INT bReverseRoll;                       // 0x14
    INT MA;                                 // 0x18
    FLOAT PctInStart;                       // 0x1C
    FLOAT PctInEnd;                         // 0x20
    FLOAT PctInDuration;                    // 0x24
    FRotator StartingRotation;              // 0x28
};
T3_CHECK_SIZE(FMatObjectOrientation, 0x34);

class AActor : public UObject
{
    DECLARE_CLASS(AActor, UObject, 0x800, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x10993EC0
    virtual ~AActor();                      // slot 2: 0x109624C0
    virtual void ProcessEvent(UFunction* Function, void* Parms, void* Result);// slot 3: 0x1098CFC0
    virtual void ProcessState(FLOAT DeltaSeconds);// slot 4: 0x109E97F0
    virtual void PostLoad();                // slot 7: 0x10993FC0
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x10995410
    virtual UBOOL IsPendingKill();          // slot 9: 0x109623C0
    virtual void InitExecution();           // slot 12: 0x109E9650
    virtual void Unknown3C();               // slot 15: 0x1098E0E0

public:
    FVector Location;                       // 0x2C
    FRotator Rotation;                      // 0x38
    FVector Velocity;                       // 0x44
    FVector Acceleration;                   // 0x50
    FVector ColLocation;                    // 0x5C
    APhysicsVolume* PhysicsVolume;          // 0x68
    UMesh* Mesh;                            // 0x6C
    AActor* DeletedActor;                   // 0x70
    BITFIELD bLocalGameEvent:1;             // 0x74
    BITFIELD bTravelGameEvent:1;
    BITFIELD bDestroyInPainVolume:1;
    BITFIELD bDontDestroy:1;
    BITFIELD bHiddenEd:1;
    BITFIELD bHiddenEdGroup:1;
    BITFIELD bDirectional:1;
    BITFIELD bEdShouldSnap:1;
    BITFIELD bShouldTickInAppTime:1;
    BITFIELD bShouldNotTick:1;
    BITFIELD bNeedsToMove:1;
    BITFIELD bOwnerNoSee:1;
    BITFIELD bOnlyOwnerSee:1;
    BITFIELD bTrailerSameRotation:1;
    BITFIELD bTrailerPrePivot:1;
    BITFIELD bWorldGeometry:1;
    BITFIELD bEdLocked:1;
    BITFIELD bEdSnap:1;
    BITFIELD bScriptInitialized:1;
    BITFIELD bHurtEntry:1;
    BITFIELD bCarriedItem:1;
    BITFIELD bTravel:1;
    BITFIELD bInterpolating:1;
    BITFIELD bJustTeleported:1;
    BITFIELD bNetInitial:1;
    BITFIELD bNetOwner:1;
    BITFIELD bNetRelevant:1;
    BITFIELD bSimulatedPawn:1;
    BITFIELD bDemoRecording:1;
    BITFIELD bClientDemoRecording:1;
    BITFIELD bClientDemoNetFunc:1;
    BITFIELD bPathColliding:1;
    BITFIELD bDeleteMe:1;                   // 0x78
    BITFIELD bTicked:1;
    BITFIELD bIsPawn:1;
    BITFIELD bAnimFinished:1;
    BITFIELD bAnimLoop:1;
    BITFIELD bAnimNotify:1;
    BITFIELD bAnimByOwner:1;
    BITFIELD bIsMover:1;
    BITFIELD bNetOptional:1;
    BITFIELD bNetTemporary:1;
    BITFIELD bAlwaysRelevant:1;
    BITFIELD bReplicateInstigator:1;
    BITFIELD bClientAnim:1;
    BITFIELD bDirty:1;
    BITFIELD bDirtyReplication:1;
    BITFIELD bAlwaysTick:1;
    BITFIELD bLightChanged:1;
    BITFIELD bDynamicLight:1;
    BITFIELD bTimerLoop:1;
    BITFIELD bMemorized:1;
    BITFIELD bHighlighted:1;
    BITFIELD bTempEditor:1;
    BITFIELD bBobbing:1;
    BITFIELD bObsolete:1;
    BITFIELD bPathTemp:1;
    BITFIELD bAcceptsProjectors:1;
    BITFIELD bSentSpawnNotification:1;
    BITFIELD bCanBeDestroyedInPreBeginPlay:1;
    BITFIELD bNoSpawnNotifications:1;
    BYTE Role;                              // 0x7C  ENetRole
    BYTE RemoteRole;                        // 0x7D  ENetRole
    BYTE ForceType;                         // 0x7E  EForceType
    FLOAT LastRenderTime;                   // 0x80
    FPointRegion Region;                    // 0x84
    INT m_FleshBSPZone;                     // 0x90
    ALevelInfo* Level;                      // 0x94
    ULevel* XLevel;                         // 0x98
    AActor* Owner;                          // 0x9C
    INT TickPhase;                          // 0xA0
    AActor* AttachedParent;                 // 0xA4
    INT CollisionTag;                       // 0xA8
    INT LightingTag;                        // 0xAC
    INT m_physicsObjectPadding;             // 0xB0
    INT m_FleshObject;                      // 0xB4
    INT m_FleshLight;                       // 0xB8
    INT m_isSelectedPadding;                // 0xBC
};
T3_CHECK_SIZE(AActor, 0xC0);

class AMetaProperty : public AActor
{
    DECLARE_CLASS(AMetaProperty, AActor, 0x0, Engine)

public:
    virtual ~AMetaProperty();               // slot 2: 0x10962700

public:
};
T3_CHECK_SIZE(AMetaProperty, 0xC0);

class ABrush : public AActor
{
    DECLARE_CLASS(ABrush, AActor, 0x0, Engine)

public:
    virtual ~ABrush();                      // slot 2: 0x1098C850
    virtual void PostLoad();                // slot 7: 0x109941C0
    virtual void Unknown3C();               // slot 15: 0x10993AD0

public:
    BYTE CsgOper;                           // 0xC0  ECsgOper
    UObject* UnusedLightMesh;               // 0xC4
    FVector PostPivot;                      // 0xC8
    FScale MainScale;                       // 0xD4
    FScale PostScale;                       // 0xE8
    FScale TempScale;                       // 0xFC
    FColor BrushColor;                      // 0x110
    INT PolyFlags;                          // 0x114
    BITFIELD bColored:1;                    // 0x118
    UObject* pStaticMesh;                   // 0x11C
};
T3_CHECK_SIZE(ABrush, 0x120);

class AVolume : public ABrush
{
    DECLARE_CLASS(AVolume, ABrush, 0x0, Engine)

public:
    virtual ~AVolume();                     // slot 2: 0x1098D0C0

public:
    FStringNoInit LocationName;             // 0x120
    FBox CachedWorldBBox;                   // 0x12C
};
T3_CHECK_SIZE(AVolume, 0x148);

class AController : public AActor
{
    DECLARE_CLASS(AController, AActor, 0x800, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x109ECDB0

public:
    APawn* Pawn;                            // 0xC0
    FLOAT FovAngle;                         // 0xC4
    BITFIELD bIsPlayer:1;                   // 0xC8
    AController* nextController;            // 0xCC
    UClass* PawnClass;                      // 0xD0
    FStringNoInit FaceName;                 // 0xD4
    FStringNoInit SkinName;                 // 0xE0
    FLOAT GroundPitchTime;                  // 0xEC
    FVector ViewX;                          // 0xF0
    FVector ViewY;                          // 0xFC
    FVector ViewZ;                          // 0x108
};
T3_CHECK_SIZE(AController, 0x114);

class AAIController : public AController
{
    DECLARE_CLASS(AAIController, AController, 0x0, Engine)

public:
    virtual ~AAIController();               // slot 2: 0x10962640

public:
};
T3_CHECK_SIZE(AAIController, 0x114);

class AMarker : public AActor
{
    DECLARE_CLASS(AMarker, AActor, 0x0, Engine)

public:
    virtual ~AMarker();                     // slot 2: 0x1098C8D0

public:
};
T3_CHECK_SIZE(AMarker, 0xC0);

class APawn : public AActor
{
    DECLARE_CLASS(APawn, AActor, 0x800, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x10A4FD70
    virtual ~APawn();                       // slot 2: 0x10A46E10
    virtual void PostLoad();                // slot 7: 0x109A6250
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x10A50120

public:
    AController* Controller;                // 0xC0
    BITFIELD bJustLanded:1;                 // 0xC4
    BITFIELD bUpAndOut:1;
    BITFIELD bIsWalking:1;
    BITFIELD bWarping:1;
    BITFIELD bWantsToCrouch:1;
    BITFIELD bTryToUncrouch:1;
    BITFIELD bIsCrouched:1;
    BITFIELD bCrawler:1;
    BITFIELD bReducedSpeed:1;
    BITFIELD bCanSwim:1;
    BITFIELD bCanFly:1;
    BITFIELD bAvoidLedges:1;
    BITFIELD bStopAtLedges:1;
    BITFIELD bNoJumpAdjust:1;
    BITFIELD bCountJumps:1;
    BITFIELD bSimulateGravity:1;
    BITFIELD bUpdateEyeheight:1;
    BITFIELD bIgnoreForces:1;
    BITFIELD bNoVelocityUpdate:1;
    BITFIELD bCanWalkOffLedges:1;
    BITFIELD bIsTurning:1;
    BITFIELD bTurningLeft:1;
    BITFIELD bThumped:1;
    BITFIELD bInvulnerableBody:1;
    BITFIELD bIsFemale:1;
    BITFIELD bAutoActivate:1;
    BITFIELD bCanPickupInventory:1;
    BITFIELD bUpdatingDisplay:1;
    BITFIELD bAmbientCreature:1;
    BYTE Visibility;                        // 0xC8
    FLOAT DesiredSpeed;                     // 0xCC
    FLOAT MaxDesiredSpeed;                  // 0xD0
    FLOAT AvgPhysicsTime;                   // 0xD4
    FLOAT MeleeRange;                       // 0xD8
    ANavigationPoint* Anchor;               // 0xDC
    FLOAT GroundSpeed;                      // 0xE0
    FLOAT WaterSpeed;                       // 0xE4
    FLOAT AirSpeed;                         // 0xE8
    FLOAT LadderSpeed;                      // 0xEC
    FLOAT AccelRate;                        // 0xF0
    FLOAT JumpZ;                            // 0xF4
    FLOAT AirControl;                       // 0xF8
    FLOAT WalkingPct;                       // 0xFC
    BITFIELD bOnSlope:1;                    // 0x100
    FLOAT SlopeStartAltitude;               // 0x104
    FLOAT InterpolatedZ;                    // 0x108
    FStringNoInit OwnerName;                // 0x10C
    FLOAT BaseEyeHeight;                    // 0x118
    FLOAT EyeHeight;                        // 0x11C
    FVector Floor;                          // 0x120
    FLOAT SplashTime;                       // 0x12C
    FLOAT CrouchHeight;                     // 0x130
    FLOAT CrouchRadius;                     // 0x134
    FLOAT OldZ;                             // 0x138
    APhysicsVolume* HeadVolume;             // 0x13C
    INT Health;                             // 0x140
    FLOAT BreathTime;                       // 0x144
    FLOAT UnderWaterTime;                   // 0x148
    FLOAT LastPainTime;                     // 0x14C
    FVector noise1spot;                     // 0x150
    FLOAT noise1time;                       // 0x15C
    APawn* noise1other;                     // 0x160
    FLOAT noise1loudness;                   // 0x164
    FVector noise2spot;                     // 0x168
    FLOAT noise2time;                       // 0x174
    APawn* noise2other;                     // 0x178
    FLOAT noise2loudness;                   // 0x17C
    FLOAT LastPainSound;                    // 0x180
    FLOAT SoundDampening;                   // 0x184
    FLOAT DamageScaling;                    // 0x188
    FStringNoInit MenuName;                 // 0x18C
    UClass* BloodEffect;                    // 0x198
    UClass* LowDetailBlood;                 // 0x19C
    UClass* LowGoreBlood;                   // 0x1A0
    UClass* ControllerClass;                // 0x1A4
    INT DemoViewPitch;                      // 0x1A8
    INT DemoViewYaw;                        // 0x1AC
    FLOAT CarcassCollisionHeight;           // 0x1B0
    FName LandMovementState;                // 0x1B4
    FName WaterMovementState;               // 0x1B8
    FName AnimStatus;                       // 0x1BC
    FName AnimAction;                       // 0x1C0
    FLOAT OldRotYaw;                        // 0x1C4
    FVector OldAcceleration;                // 0x1C8
    BITFIELD bZombieIgnoreBody:1;           // 0x1D4
    FLOAT LODDistanceOff;                   // 0x1D8
    FLOAT LODDistanceMinimal;               // 0x1DC
    FLOAT LODDistanceBasic;                 // 0x1E0
    BITFIELD IsBlinded:1;                   // 0x1E4
    BITFIELD IsHacking:1;
    FLOAT InvisibilityTargetAlpha;          // 0x1E8
    FLOAT InvisibilityInterpolationRate;    // 0x1EC
    FLOAT InvisibilityCurrentAlpha;         // 0x1F0
    FLOAT InvisibilityEndTime;              // 0x1F4
    INT DArrayPad[3];                       // 0x1F8
    INT InventoryPtrStub;                   // 0x204
};
T3_CHECK_SIZE(APawn, 0x208);

class AAmbientLightVolume : public AVolume
{
    DECLARE_CLASS(AAmbientLightVolume, AVolume, 0x800, Engine)

public:
    virtual ~AAmbientLightVolume();         // slot 2: 0x109942F0

public:
};
T3_CHECK_SIZE(AAmbientLightVolume, 0x148);

class APlayerController : public AController
{
    DECLARE_CLASS(APlayerController, AController, 0x804, Engine)

public:
    virtual ~APlayerController();           // slot 2: 0x1098D300

public:
    UPlayer* Player;                        // 0x114
    BITFIELD bLookUpStairs:1;               // 0x118
    BITFIELD bSnapToLevel:1;
    BITFIELD bAlwaysMouseLook:1;
    BITFIELD bKeyboardLook:1;
    BITFIELD bCenterView:1;
    BITFIELD bBehindView:1;
    BITFIELD bFrozen:1;
    BITFIELD bPressedJump:1;
    BITFIELD bUpdatePosition:1;
    BITFIELD bJustFired:1;
    BITFIELD bJustAltFired:1;
    BITFIELD bIsTyping:1;
    BITFIELD bFixedCamera:1;
    BITFIELD bJumpStatus:1;
    BITFIELD bUpdating:1;
    BITFIELD bInvertYLookAxis:1;
    BITFIELD bDesiresToBePlanted:1;
    BITFIELD bNeverSwitchOnPickup:1;
    BITFIELD bZooming:1;
    BITFIELD bOnlySpectator:1;
    BITFIELD bAlwaysLevel:1;
    BITFIELD bSetTurnRot:1;
    BITFIELD bCheatFlying:1;
    BITFIELD bFreeCamera:1;
    FLOAT AimingHelp;                       // 0x11C
    FLOAT WaitDelay;                        // 0x120
    FLOAT aBaseX;                           // 0x124
    FLOAT aBaseY;                           // 0x128
    FLOAT aBaseZ;                           // 0x12C
    FLOAT aMouseX;                          // 0x130
    FLOAT aMouseY;                          // 0x134
    FLOAT aForward;                         // 0x138
    FLOAT aTurn;                            // 0x13C
    FLOAT aStrafe;                          // 0x140
    FLOAT aUp;                              // 0x144
    FLOAT aLookUp;                          // 0x148
    BYTE bStrafe;                           // 0x14C
    BYTE bSnapLevel;                        // 0x14D
    BYTE bLook;                             // 0x14E
    BYTE bFreeLook;                         // 0x14F
    BYTE bTurn180;                          // 0x150
    BYTE bTurnToNearest;                    // 0x151
    BYTE DoubleClickDir;                    // 0x152  EDoubleClickDir
    INT Misc1;                              // 0x154
    INT Misc2;                              // 0x158
    INT RendMap;                            // 0x15C
    FLOAT OrthoZoom;                        // 0x160
    AActor* ViewTarget;                     // 0x164
    FLOAT CameraDist;                       // 0x168
    FLOAT DesiredFOV;                       // 0x16C
    FLOAT DefaultFOV;                       // 0x170
    FLOAT ZoomLevel;                        // 0x174
    FVector FlashScale;                     // 0x178
    FVector FlashFog;                       // 0x184
    FLOAT DesiredFlashScale;                // 0x190
    FLOAT ConstantGlowScale;                // 0x194
    FLOAT InstantFlash;                     // 0x198
    FVector DesiredFlashFog;                // 0x19C
    FVector ConstantGlowFog;                // 0x1A8
    FVector InstantFog;                     // 0x1B4
    FRotator TargetViewRotation;            // 0x1C0
    FLOAT TargetEyeHeight;                  // 0x1CC
    FVector TargetWeaponViewOffset;         // 0x1D0
    FLOAT LastPlaySound;                    // 0x1DC
    INT AnnouncerVolume;                    // 0x1E0
    FLOAT CurrentTimeStamp;                 // 0x1E4
    FLOAT LastUpdateTime;                   // 0x1E8
    FLOAT ServerTimeStamp;                  // 0x1EC
    FLOAT TimeMargin;                       // 0x1F0
    FLOAT ClientUpdateTime;                 // 0x1F4
    FLOAT MaxTimeMargin;                    // 0x1F8
    INT WeaponUpdate;                       // 0x1FC
    FStringNoInit ProgressMessage[4];       // 0x200
    FColor ProgressColor[4];                // 0x230
    FLOAT ProgressTimeOut;                  // 0x240
    FStringNoInit QuickSaveString;          // 0x244
    FStringNoInit NoPauseMessage;           // 0x250
    FStringNoInit ViewingFrom;              // 0x25C
    FStringNoInit OwnCamera;                // 0x268
    FStringNoInit ngWorldSecret;            // 0x274
    BITFIELD ngSecretSet:1;                 // 0x280
    BITFIELD ReceivedSecretChecksum:1;
    FLOAT Bob;                              // 0x284
    FLOAT LandBob;                          // 0x288
    FLOAT AppliedBob;                       // 0x28C
    FLOAT bobtime;                          // 0x290
    APawn* TurnTarget;                      // 0x294
    INT EnemyTurnSpeed;                     // 0x298
    INT GroundPitch;                        // 0x29C
    FRotator TurnRot180;                    // 0x2A0
    FVector OldFloor;                       // 0x2AC
    INT ShowFlags[2];                       // 0x2B8
};
T3_CHECK_SIZE(APlayerController, 0x2C0);

class ACamera : public APlayerController
{
    DECLARE_CLASS(ACamera, APlayerController, 0x4, Engine)

public:
    virtual ~ACamera();                     // slot 2: 0x1098D350

public:
};
T3_CHECK_SIZE(ACamera, 0x2C0);

class AKeypoint : public AMarker
{
    DECLARE_CLASS(AKeypoint, AMarker, 0x0, Engine)

public:
    virtual ~AKeypoint();                   // slot 2: 0x1098C950

public:
};
T3_CHECK_SIZE(AKeypoint, 0xC0);

class ACameraPoint : public AKeypoint
{
    DECLARE_CLASS(ACameraPoint, AKeypoint, 0x0, Engine)

public:
    virtual ~ACameraPoint();                // slot 2: 0x1098D5C0

public:
};
T3_CHECK_SIZE(ACameraPoint, 0xC0);

class AMetaData : public AActor
{
    DECLARE_CLASS(AMetaData, AActor, 0x0, Engine)

public:
    virtual ~AMetaData();                   // slot 2: 0x1098CA50

public:
};
T3_CHECK_SIZE(AMetaData, 0xC0);

class AInfo : public AMetaData
{
    DECLARE_CLASS(AInfo, AMetaData, 0x0, Engine)

public:
    virtual ~AInfo();                       // slot 2: 0x1098CAD0

public:
};
T3_CHECK_SIZE(AInfo, 0xC0);

class AClipMarker : public AKeypoint
{
    DECLARE_CLASS(AClipMarker, AKeypoint, 0x0, Engine)

public:
    virtual ~AClipMarker();                 // slot 2: 0x1098D670

public:
};
T3_CHECK_SIZE(AClipMarker, 0xC0);

class ADeathWaterVolume : public AVolume
{
    DECLARE_CLASS(ADeathWaterVolume, AVolume, 0x800, Engine)

public:
    virtual ~ADeathWaterVolume();           // slot 2: 0x10994390

public:
};
T3_CHECK_SIZE(ADeathWaterVolume, 0x148);

class APhysicsVolume : public AVolume
{
    DECLARE_CLASS(APhysicsVolume, AVolume, 0x800, Engine)

public:
    virtual ~APhysicsVolume();              // slot 2: 0x1098D140

public:
    FVector ViewFlash;                      // 0x148
    FVector ViewFog;                        // 0x154
    FVector Gravity;                        // 0x160
    BITFIELD bDistanceFog:1;                // 0x16C
    FColor DistanceFogColor;                // 0x170
    FLOAT DistanceFogStart;                 // 0x174
    FLOAT DistanceFogEnd;                   // 0x178
};
T3_CHECK_SIZE(APhysicsVolume, 0x17C);

class ADefaultPhysicsVolume : public APhysicsVolume
{
    DECLARE_CLASS(ADefaultPhysicsVolume, APhysicsVolume, 0x0, Engine)

public:
    virtual ~ADefaultPhysicsVolume();       // slot 2: 0x10994450

public:
};
T3_CHECK_SIZE(ADefaultPhysicsVolume, 0x17C);

class AElevatorFloors : public AMetaData
{
    DECLARE_CLASS(AElevatorFloors, AMetaData, 0x0, Engine)

public:
    virtual ~AElevatorFloors();             // slot 2: 0x1098DC50

public:
};
T3_CHECK_SIZE(AElevatorFloors, 0xC0);

class AFX : public AActor
{
    DECLARE_CLASS(AFX, AActor, 0x0, Engine)

public:
    virtual ~AFX();                         // slot 2: 0x1098D400

public:
};
T3_CHECK_SIZE(AFX, 0xC0);

class AEmitter : public AFX
{
    DECLARE_CLASS(AEmitter, AFX, 0x0, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x109966F0
    virtual ~AEmitter();                    // slot 2: 0x109973B0
    virtual void PostLoad();                // slot 7: 0x10996810
    virtual void Unknown3C();               // slot 15: 0x10996490
    virtual void Unknown40();               // slot 16: 0x10996600

public:
    FLOAT TimeSinceRendered;                // 0xC0
    FRotator PreviousRotation;              // 0xC4
    FVector PreviousLocation;               // 0xD0
    TArray<UParticleEmitter*> Emitters;     // 0xDC
    BITFIELD AutoDestroy:1;                 // 0xE8
    BITFIELD AutoReset:1;
    BITFIELD DisableFogging:1;
    BITFIELD bDisableZBuffer:1;
    BITFIELD bRenderedLastFrame:1;
    BITFIELD ActorForcesEnabled:1;
    BITFIELD AutoHide:1;
    FRangeVector GlobalOffsetRange;         // 0xEC
    FRange TimeTillResetRange;              // 0x104
    FBox BoundingBox;                       // 0x10C
    FLOAT EmitterRadius;                    // 0x128
    FLOAT EmitterHeight;                    // 0x12C
    FVector GlobalOffset;                   // 0x130
    FLOAT TimeTillReset;                    // 0x13C
    BITFIELD InOverlay:1;                   // 0x140
};
T3_CHECK_SIZE(AEmitter, 0x144);

class APlayerPawn : public APawn
{
    DECLARE_CLASS(APlayerPawn, APawn, 0x0, Engine)

public:
    virtual ~APlayerPawn();                 // slot 2: 0x10A47700
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x10A464D0

public:
    TArray<FsGoal> Goals;                   // 0x208
    TArray<FsCitySectionGoal> CitySectionGoals; // 0x214
    TArray<FsNote> PlayerNotes;             // 0x220
    TArray<INT> BoneIndicesForLightLevelCalc; // 0x22C
    TArray<FLightLevelInfo> LightLevels;    // 0x238
    INT BoneToUseForLightCalc;              // 0x244
    INT LightLevelCalculationsPerFrame;     // 0x248
    FLOAT InterpolatedLightLevel;           // 0x24C
    FsLightLevelDebugInfo LightLevelDebugInfo; // 0x250
    FLOAT TotalPlayTime;                    // 0x26C
    FLOAT SimtimePlayedTimer;               // 0x270
    INT TravelDisabledTokens;               // 0x274
};
T3_CHECK_SIZE(APlayerPawn, 0x278);

class AInterpolationPoint : public AKeypoint
{
    DECLARE_CLASS(AInterpolationPoint, AKeypoint, 0x0, Engine)

public:
    virtual ~AInterpolationPoint();         // slot 2: 0x1098D720
    virtual void Unknown3C();               // slot 15: 0x1099AB10

public:
};
T3_CHECK_SIZE(AInterpolationPoint, 0xC0);

class AZoneInfo : public AInfo
{
    DECLARE_CLASS(AZoneInfo, AInfo, 0x800, Engine)

public:
    virtual ~AZoneInfo();                   // slot 2: 0x10992D20

public:
    ASkyZoneInfo* SkyZone;                  // 0xC0
    FName ZoneTag;                          // 0xC4
    BITFIELD bFogZone:1;                    // 0xC8
    BITFIELD bTerrainZone:1;
    BITFIELD bDistanceFog:1;
    TArray<ATerrainInfo*> Terrains;         // 0xCC
    FColor AmbientColor;                    // 0xD8
    BYTE AmbientBrightness;                 // 0xDC
    BYTE AmbientHue;                        // 0xDD
    BYTE AmbientSaturation;                 // 0xDE
    BYTE PadDF[0x1];
    FColor DistanceFogColor;                // 0xE0
    FLOAT DistanceFogStart;                 // 0xE4
    FLOAT DistanceFogEnd;                   // 0xE8
    UTexture* EnvironmentMap;               // 0xEC
    FLOAT TexUPanSpeed;                     // 0xF0
    FLOAT TexVPanSpeed;                     // 0xF4
    BITFIELD bReverbZone:1;                 // 0xF8
    BITFIELD bRaytraceReverb:1;
    FLOAT SpeedOfSound;                     // 0xFC
    BYTE MasterGain;                        // 0x100
    INT CutoffHz;                           // 0x104
    BYTE Delay[6];                          // 0x108
    BYTE Gain[6];                           // 0x10E
    UTexture* LensFlare[12];                // 0x114
    FLOAT LensFlareOffset[12];              // 0x144
    FLOAT LensFlareScale[12];               // 0x174
    BYTE MinLightCount;                     // 0x1A4
    BYTE MaxLightCount;                     // 0x1A5
    INT MinLightingPolyCount;               // 0x1A8
    INT MaxLightingPolyCount;               // 0x1AC
};
T3_CHECK_SIZE(AZoneInfo, 0x1B0);

class ALevelInfo : public AZoneInfo
{
    DECLARE_CLASS(ALevelInfo, AZoneInfo, 0x800, Engine)

public:
    virtual ~ALevelInfo();                  // slot 2: 0x10992E50

public:
    FLOAT TimeSeconds;                      // 0x1B0
    INT Year;                               // 0x1B4
    INT Month;                              // 0x1B8
    INT Day;                                // 0x1BC
    INT DayOfWeek;                          // 0x1C0
    INT Hour;                               // 0x1C4
    INT Minute;                             // 0x1C8
    INT Second;                             // 0x1CC
    INT Millisecond;                        // 0x1D0
    FStringNoInit Title;                    // 0x1D4
    FStringNoInit Author;                   // 0x1E0
    INT IdealPlayerCount;                   // 0x1EC
    FStringNoInit LevelEnterText;           // 0x1F0
    FStringNoInit LocalizedPkg;             // 0x1FC
    INT MapNumber;                          // 0x208
    FStringNoInit VisibleGroups;            // 0x20C
    BITFIELD bLonePlayer:1;                 // 0x218
    BITFIELD bBegunPlay:1;
    BITFIELD bPlayersOnly:1;
    BITFIELD bHighDetailMode:1;
    BITFIELD bDropDetail:1;
    BITFIELD bAggressiveLOD:1;
    BITFIELD bStartup:1;
    BITFIELD bPathsRebuilt:1;
    BITFIELD bIsCitySection:1;
    FVector CameraLocationDynamic;          // 0x21C
    FVector CameraLocationTop;              // 0x228
    FVector CameraLocationFront;            // 0x234
    FVector CameraLocationSide;             // 0x240
    FRotator CameraRotationDynamic;         // 0x24C
    FStringNoInit CitySectionName;          // 0x258
    FLOAT Brightness;                       // 0x264
    UTexture* Screenshot;                   // 0x268
    UTexture* DefaultTexture;               // 0x26C
    UTexture* WireframeTexture;             // 0x270
    UTexture* WhiteSquareTexture;           // 0x274
    INT HubStackLevel;                      // 0x278
    BYTE LevelAction;                       // 0x27C  ELevelAction
    BITFIELD bNeverPrecache:1;              // 0x280
    BYTE NetMode;                           // 0x284  ENetMode
    FStringNoInit ComputerName;             // 0x288
    FStringNoInit EngineVersion;            // 0x294
    FStringNoInit MinNetVersion;            // 0x2A0
    FStringNoInit ConversationPackage;      // 0x2AC
    FStringNoInit DefaultGameType;          // 0x2B8
    ANavigationPoint* NavigationPointList;  // 0x2C4
    AController* ControllerList;            // 0x2C8
    FStringNoInit NextURL;                  // 0x2CC
    BITFIELD bNextItems:1;                  // 0x2D8
    FLOAT NextSwitchCountdown;              // 0x2DC
    BITFIELD bSavedBuildInfo:1;             // 0x2E0
    INT BSPOptSetting;                      // 0x2E4
    INT RebuildFlags;                       // 0x2E8
    INT BSPTreeBalance;                     // 0x2EC
    INT BSPPortalBias;                      // 0x2F0
    INT NavMeshBuildFlags;                  // 0x2F4
    FLOAT MinTimeBetweenAmbientBarks;       // 0x2F8
    FLOAT MinTimeBetweenNearObjectBarks;    // 0x2FC
    FLOAT NearObjectBarkTimestamp;          // 0x300
    FLOAT NearShadowMaxDistanceToPlayer;    // 0x304
    FLOAT NearShadowMaxLightLevel;          // 0x308
    FLOAT SearchContinueBarkMinTimer;       // 0x30C
    FLOAT SearchContinueBarkMaxTimer;       // 0x310
    FLOAT SearchUpdateBarkMinTimer;         // 0x314
    FLOAT SearchUpdateBarkMaxTimer;         // 0x318
    FLOAT FrustrationBarkMinTimer;          // 0x31C
    FLOAT FrustrationBarkMaxTimer;          // 0x320
    FLOAT CombatBarkMinTimer;               // 0x324
    FLOAT CombatBarkMaxTimer;               // 0x328
    FLOAT DefensiveSpellUsageMinTimer;      // 0x32C
    FLOAT DefensiveSpellUsageMaxTimer;      // 0x330
    FLOAT TimeBetweenInformBehaviors;       // 0x334
    FLOAT InformCharacterDistance;          // 0x338
    FLOAT InformBehaviorTimeout;            // 0x33C
};
T3_CHECK_SIZE(ALevelInfo, 0x340);

class ALight : public AActor
{
    DECLARE_CLASS(ALight, AActor, 0x0, Engine)

public:
    virtual ~ALight();                      // slot 2: 0x1098D4B0

public:
    FVector CoronaSize;                     // 0xC0
};
T3_CHECK_SIZE(ALight, 0xCC);

class ALookTarget : public AKeypoint
{
    DECLARE_CLASS(ALookTarget, AKeypoint, 0x0, Engine)

public:
    virtual ~ALookTarget();                 // slot 2: 0x109976E0

public:
};
T3_CHECK_SIZE(ALookTarget, 0xC0);

class AMissingArch : public AActor
{
    DECLARE_CLASS(AMissingArch, AActor, 0x8, Engine)

public:
    virtual ~AMissingArch();                // slot 2: 0x1098DE90

public:
};
T3_CHECK_SIZE(AMissingArch, 0xC0);

class ANavigationPoint : public AKeypoint
{
    DECLARE_CLASS(ANavigationPoint, AKeypoint, 0x0, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x10A3D8B0
    virtual ~ANavigationPoint();            // slot 2: 0x1098C9D0

public:
    INT upstreamPaths[16];                  // 0xC0
    INT Paths[16];                          // 0x100
    INT PrunedPaths[16];                    // 0x140
    FName ProscribedPaths[4];               // 0x180
    FName ForcedPaths[4];                   // 0x190
    INT visitedWeight;                      // 0x1A0
    AActor* RouteCache;                     // 0x1A4
    INT bestPathWeight;                     // 0x1A8
    ANavigationPoint* nextNavigationPoint;  // 0x1AC
    ANavigationPoint* nextOrdered;          // 0x1B0
    ANavigationPoint* prevOrdered;          // 0x1B4
    ANavigationPoint* previousPath;         // 0x1B8
    INT cost;                               // 0x1BC
    INT ExtraCost;                          // 0x1C0
    BITFIELD bEndPoint:1;                   // 0x1C4
    BITFIELD bEndPointOnly:1;
    BITFIELD bSpecialCost:1;
    BITFIELD taken:1;
    BITFIELD bBlocked:1;
    BITFIELD bPropagatesSound:1;
    BITFIELD bOneWayPath:1;
    BITFIELD bNeverUseStrafing:1;
    BITFIELD bAutoBuilt:1;
    BITFIELD bSpecialMove:1;
    BITFIELD bNoAutoConnect:1;
    BITFIELD bNotBased:1;
    BITFIELD bAutoPlaced:1;
};
T3_CHECK_SIZE(ANavigationPoint, 0x1C8);

class ANorthMarker : public ANavigationPoint
{
    DECLARE_CLASS(ANorthMarker, ANavigationPoint, 0x0, Engine)

public:
    virtual ~ANorthMarker();                // slot 2: 0x1098D800

public:
};
T3_CHECK_SIZE(ANorthMarker, 0x1C8);

class AObjSysTest : public AActor
{
    DECLARE_CLASS(AObjSysTest, AActor, 0x0, Engine)

public:
    virtual ~AObjSysTest();                 // slot 2: 0x1098CB50

public:
};
T3_CHECK_SIZE(AObjSysTest, 0xC0);

class AObjSysTestChild : public AObjSysTest
{
    DECLARE_CLASS(AObjSysTestChild, AObjSysTest, 0x0, Engine)

public:
    virtual ~AObjSysTestChild();            // slot 2: 0x1098DF70

public:
};
T3_CHECK_SIZE(AObjSysTestChild, 0xC0);

class APathNode : public ANavigationPoint
{
    DECLARE_CLASS(APathNode, ANavigationPoint, 0x0, Engine)

public:
    virtual ~APathNode();                   // slot 2: 0x1098D8B0

public:
};
T3_CHECK_SIZE(APathNode, 0x1C8);

class APlayerStart : public ANavigationPoint
{
    DECLARE_CLASS(APlayerStart, ANavigationPoint, 0x0, Engine)

public:
    virtual ~APlayerStart();                // slot 2: 0x1098D960

public:
    BYTE TeamNumber;                        // 0x1C8
    BITFIELD bSinglePlayerStart:1;          // 0x1CC
    BITFIELD bCoopStart:1;
    BITFIELD bEnabled:1;
};
T3_CHECK_SIZE(APlayerStart, 0x1D0);

class APolyMarker : public AKeypoint
{
    DECLARE_CLASS(APolyMarker, AKeypoint, 0x0, Engine)

public:
    virtual ~APolyMarker();                 // slot 2: 0x1098DA10

public:
};
T3_CHECK_SIZE(APolyMarker, 0xC0);

class ASceneManager : public AInfo
{
    DECLARE_CLASS(ASceneManager, AInfo, 0x4, Engine)

public:
    virtual ~ASceneManager();               // slot 2: 0x1099ADD0
    virtual void Unknown3C();               // slot 15: 0x1099AAE0

public:
    TArray<UMatAction*> Actions;            // 0xC0
    BYTE Affect;                            // 0xCC  EAffect
    AActor* AffectedActor;                  // 0xD0
    BITFIELD bLooping:1;                    // 0xD4
    BITFIELD bCinematicView:1;
    FLOAT PctSceneComplete;                 // 0xD8
    UMatAction* CurrentAction;              // 0xDC
    FLOAT SceneSpeed;                       // 0xE0
    FLOAT TotalSceneTime;                   // 0xE4
    AActor* Viewer;                         // 0xE8
    APawn* OldPawn;                         // 0xEC
    BITFIELD bIsRunning:1;                  // 0xF0
    BITFIELD bIsSceneStarted:1;
    FLOAT CurrentTime;                      // 0xF4
    TArray<FVector> SampleLocations;        // 0xF8
    TArray<UMatSubAction*> SubActions;      // 0x104
    FOrientation CamOrientation;            // 0x110
    FOrientation PrevOrientation;           // 0x144
    INT pad0;                               // 0x178
};
T3_CHECK_SIZE(ASceneManager, 0x17C);

class AShallowWaterVolume : public AVolume
{
    DECLARE_CLASS(AShallowWaterVolume, AVolume, 0x800, Engine)

public:
    virtual ~AShallowWaterVolume();         // slot 2: 0x109944F0

public:
};
T3_CHECK_SIZE(AShallowWaterVolume, 0x148);

class ASkyZoneInfo : public AZoneInfo
{
    DECLARE_CLASS(ASkyZoneInfo, AZoneInfo, 0x0, Engine)

public:
    virtual ~ASkyZoneInfo();                // slot 2: 0x10992FB0

public:
};
T3_CHECK_SIZE(ASkyZoneInfo, 0x1B0);

class ASpecialOptions : public AMetaData
{
    DECLARE_CLASS(ASpecialOptions, AMetaData, 0x0, Engine)

public:
    virtual ~ASpecialOptions();             // slot 2: 0x1098DDE0

public:
};
T3_CHECK_SIZE(ASpecialOptions, 0xC0);

class AStaticMeshActor : public AActor
{
    DECLARE_CLASS(AStaticMeshActor, AActor, 0x0, Engine)

public:
    virtual ~AStaticMeshActor();            // slot 2: 0x10970530

public:
};
T3_CHECK_SIZE(AStaticMeshActor, 0xC0);

class AStimulusModifierObject : public AMetaProperty
{
    DECLARE_CLASS(AStimulusModifierObject, AMetaProperty, 0x0, Engine)

public:
    virtual ~AStimulusModifierObject();     // slot 2: 0x1099BA20

public:
};
T3_CHECK_SIZE(AStimulusModifierObject, 0xC0);

class ASwooshEffectObject : public AMetaProperty
{
    DECLARE_CLASS(ASwooshEffectObject, AMetaProperty, 0x0, Engine)

public:
    virtual ~ASwooshEffectObject();         // slot 2: 0x1099BAC0

public:
};
T3_CHECK_SIZE(ASwooshEffectObject, 0xC0);

class ATerrainInfo : public AInfo
{
    DECLARE_CLASS(ATerrainInfo, AInfo, 0x0, Engine)

public:
    virtual ~ATerrainInfo();                // slot 2: 0x109D1430

public:
    UTexture* TerrainMap;                   // 0xC0
    FVector TerrainScale;                   // 0xC4
    FTerrainLayer Layers[32];               // 0xD0
    TArray<FDecorationLayer> DecoLayers;    // 0x650
    INT DummyTerrainPadding[4];             // 0x65C
    TArray<UTerrainSector*> Sectors;        // 0x66C
    TArray<FVector> Vertices;               // 0x678
    INT HeightmapX;                         // 0x684
    INT HeightmapY;                         // 0x688
    INT SectorsX;                           // 0x68C
    INT SectorsY;                           // 0x690
    UTerrainPrimitive* Primitive;           // 0x694
    TArray<FNormalPair> FaceNormals;        // 0x698
    FVector ToWorld[4];                     // 0x6A4
    FVector ToHeightmap[4];                 // 0x6D4
    TArray<INT> SelectedVertices;           // 0x704
    INT ShowGrid;                           // 0x710
    TArray<INT> QuadVisibilityBitmap;       // 0x714
    TArray<INT> EdgeTurnBitmap;             // 0x720
    UTexture* OldTerrainMap;                // 0x72C
    TArray<BYTE> OldHeightmap;              // 0x730
};
T3_CHECK_SIZE(ATerrainInfo, 0x73C);

class AVulnerabilityObject : public AMetaProperty
{
    DECLARE_CLASS(AVulnerabilityObject, AMetaProperty, 0x0, Engine)

public:
    virtual ~AVulnerabilityObject();        // slot 2: 0x1099BB60

public:
};
T3_CHECK_SIZE(AVulnerabilityObject, 0xC0);

class AWaypoint : public AKeypoint
{
    DECLARE_CLASS(AWaypoint, AKeypoint, 0x0, Engine)

public:
    virtual ~AWaypoint();                   // slot 2: 0x1098DAC0

public:
    FLOAT PauseTime;                        // 0xC0
};
T3_CHECK_SIZE(AWaypoint, 0xC4);

class AWaypointMarker : public AKeypoint
{
    DECLARE_CLASS(AWaypointMarker, AKeypoint, 0x0, Engine)

public:
    virtual ~AWaypointMarker();             // slot 2: 0x1098DB70

public:
};
T3_CHECK_SIZE(AWaypointMarker, 0xC0);

class AZoneProperties : public AInfo
{
    DECLARE_CLASS(AZoneProperties, AInfo, 0x0, Engine)

public:
    virtual ~AZoneProperties();             // slot 2: 0x1098DD30

public:
    BITFIELD bZoneVisited:1;                // 0xC0
};
T3_CHECK_SIZE(AZoneProperties, 0xC4);

class UAISubsystem : public USubsystem
{
    DECLARE_CLASS(UAISubsystem, USubsystem, 0xD, Engine)

public:
    BYTE Pad30[0x4];
};
T3_CHECK_SIZE(UAISubsystem, 0x34);

class UMatObject : public UObject
{
    DECLARE_CLASS(UMatObject, UObject, 0x0, Engine)

public:
    virtual ~UMatObject();                  // slot 2: 0x109977D0

public:
};
T3_CHECK_SIZE(UMatObject, 0x2C);

class UMatAction : public UMatObject
{
    DECLARE_CLASS(UMatAction, UMatObject, 0x0, Engine)

public:
    virtual ~UMatAction();                  // slot 2: 0x1099A450
    virtual void Unknown3C();               // slot 15: 0x1099AAF0

public:
    AInterpolationPoint* IntPoint;          // 0x2C
    FStringNoInit Comment;                  // 0x30
    FLOAT Duration;                         // 0x3C
    TArray<UMatSubAction*> SubActions;      // 0x40
    BITFIELD bSmoothCorner:1;               // 0x4C
    FVector StartControlPoint;              // 0x50
    FVector EndControlPoint;                // 0x5C
    TArray<FVector> SampleLocations;        // 0x68
    FLOAT PctStarting;                      // 0x74
    FLOAT PctEnding;                        // 0x78
    FLOAT PctDuration;                      // 0x7C
};
T3_CHECK_SIZE(UMatAction, 0x80);

class UActionMoveCamera : public UMatAction
{
    DECLARE_CLASS(UActionMoveCamera, UMatAction, 0x4, Engine)

public:
    virtual ~UActionMoveCamera();           // slot 2: 0x1099AF20

public:
    BYTE PathStyle;                         // 0x80  EPathStyle
};
T3_CHECK_SIZE(UActionMoveCamera, 0x84);

class UActionPause : public UMatAction
{
    DECLARE_CLASS(UActionPause, UMatAction, 0x0, Engine)

public:
    virtual ~UActionPause();                // slot 2: 0x1099AFC0

public:
};
T3_CHECK_SIZE(UActionPause, 0x80);

class UAlarmLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UAlarmLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UAlarmLinkDataObject();        // slot 2: 0x1099F2C0

public:
};
T3_CHECK_SIZE(UAlarmLinkDataObject, 0x50);

class UAmmoLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UAmmoLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UAmmoLinkDataObject();         // slot 2: 0x1099F350

public:
    FLOAT m_amount;                         // 0x50
};
T3_CHECK_SIZE(UAmmoLinkDataObject, 0x54);

class UAssociationLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UAssociationLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UAssociationLinkDataObject();  // slot 2: 0x1099F3E0

public:
};
T3_CHECK_SIZE(UAssociationLinkDataObject, 0x50);

class UAttachmentLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UAttachmentLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UAttachmentLinkDataObject();   // slot 2: 0x1099F520

public:
    FStringNoInit m_attachmentBone;         // 0x50
    FStringNoInit m_parentBone;             // 0x5C
    BITFIELD bPropagatesHighlight:1;        // 0x68
    INT m_attachmentBoneIndex;              // 0x6C
    INT m_parentBoneIndex;                  // 0x70
};
T3_CHECK_SIZE(UAttachmentLinkDataObject, 0x74);

class UParticleEmitter : public UObject
{
    DECLARE_CLASS(UParticleEmitter, UObject, 0x0, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x109A67D0
    virtual ~UParticleEmitter();            // slot 2: 0x109A9EE0
    virtual void PostLoad();                // slot 7: 0x109A67B0
    virtual void Unknown3C();               // slot 15: 0x10D660B0
    virtual void Unknown40();               // slot 16: 0x109A6BB0

public:
    FVector Acceleration;                   // 0x2C
    BITFIELD UseCollision:1;                // 0x38
    FVector ExtentMultiplier;               // 0x3C
    FRangeVector DampingFactorRange;        // 0x48
    BITFIELD UseCollisionPlanes:1;          // 0x60
    BITFIELD UseGridCollisionPlanes:1;
    TArray<FPlane> CollisionPlanes;         // 0x64
    BITFIELD UseMaxCollisions:1;            // 0x70
    FRange MaxCollisions;                   // 0x74
    INT SpawnFromOtherEmitter;              // 0x7C
    INT SpawnAmount;                        // 0x80
    FRangeVector SpawnedVelocityScaleRange; // 0x84
    BITFIELD UseSpawnedVelocityScale:1;     // 0x9C
    BITFIELD UseColorScale:1;
    TArray<FParticleColorScale> ColorScale; // 0xA0
    FLOAT ColorScaleRepeats;                // 0xAC
    FPlane FadeOutFactor;                   // 0xB0
    FLOAT FadeOutStartTime;                 // 0xC0
    BITFIELD FadeOut:1;                     // 0xC4
    FPlane FadeInFactor;                    // 0xC8
    FLOAT FadeInEndTime;                    // 0xD8
    BITFIELD FadeIn:1;                      // 0xDC
    BITFIELD UseActorForces:1;
    BYTE CoordinateSystem;                  // 0xE0  EParticleCoordinateSystem
    INT MaxParticles;                       // 0xE4
    BITFIELD ResetAfterChange:1;            // 0xE8
    BYTE EffectAxis;                        // 0xEC  EParticleEffectAxis
    BITFIELD RespawnDeadParticles:1;        // 0xF0
    BITFIELD AutoDestroy:1;
    BITFIELD AutoReset:1;
    BITFIELD disabled:1;
    BITFIELD DisableFogging:1;
    FRange AutoResetTimeRange;              // 0xF4
    FStringNoInit Name;                     // 0xFC
    FVector StartLocationOffset;            // 0x108
    FRangeVector StartLocationRange;        // 0x114
    INT AddLocationFromOtherEmitter;        // 0x12C
    BYTE StartLocationShape;                // 0x130  EParticleStartLocationShape
    FRange SphereRadiusRange;               // 0x134
    FRange StartMassRange;                  // 0x13C
    BYTE UseRotationFrom;                   // 0x144  EParticleRotationSource
    BITFIELD DampRotation:1;                // 0x148
    BITFIELD SpinParticles:1;
    FRotator RotationOffset;                // 0x14C
    FLOAT SpinCCWorCWChance;                // 0x158
    FRangeVector SpinsPerSecondRange;       // 0x15C
    FRangeVector StartSpinRange;            // 0x174
    FRange SpinDampingFactorRange;          // 0x18C
    FVector RotationNormal;                 // 0x194
    BITFIELD UseSizeScale:1;                // 0x1A0
    BITFIELD UseRegularSizeScale:1;
    TArray<FParticleTimeScale> SizeScale;   // 0x1A4
    FLOAT SizeScaleRepeats;                 // 0x1B0
    FRangeVector StartSizeRange;            // 0x1B4
    BITFIELD UniformSize:1;                 // 0x1CC
    FLOAT ParticlesPerSecond;               // 0x1D0
    FLOAT InitialParticlesPerSecond;        // 0x1D4
    BITFIELD AutomaticInitialSpawning:1;    // 0x1D8
    BYTE DrawStyle;                         // 0x1DC  EParticleDrawStyle
    UTexture* Texture;                      // 0x1E0
    INT TextureUSubdivisions;               // 0x1E4
    INT TextureVSubdivisions;               // 0x1E8
    BITFIELD BlendBetweenSubdivisions:1;    // 0x1EC
    BITFIELD UseSubdivisionScale:1;
    TArray<FLOAT> SubdivisionScale;         // 0x1F0
    INT SubdivisionStart;                   // 0x1FC
    INT SubdivisionEnd;                     // 0x200
    INT SubdivisionLoops;                   // 0x204
    BITFIELD UseRandomSubdivision:1;        // 0x208
    FLOAT SecondsBeforeInactive;            // 0x20C
    FLOAT MinSquaredVelocity;               // 0x210
    FRange InitialTimeRange;                // 0x214
    FRange LifetimeRange;                   // 0x21C
    FRange InitialDelayRange;               // 0x224
    FRangeVector StartVelocityRange;        // 0x22C
    FVector MaxAbsVelocity;                 // 0x244
    FRangeVector VelocityLossRange;         // 0x250
    BITFIELD bUseVelocityClamping:1;        // 0x268
    BITFIELD bUseVelocityLoss:1;
    FVector CurrentVelocityLoss;            // 0x26C
    INT AddVelocityFromOtherEmitter;        // 0x278
    BYTE GetVelocityDirectionFrom;          // 0x27C  EParticleVelocityDirection
    FLOAT WarmupTicksPerSecond;             // 0x280
    FLOAT RelativeWarmupTime;               // 0x284
    AEmitter* Owner;                        // 0x288
    UObject* OuterObject;                   // 0x28C
    BITFIELD Initialized:1;                 // 0x290
    BITFIELD Inactive:1;
    FLOAT InactiveTime;                     // 0x294
    TArray<FParticle> Particles;            // 0x298
    INT ParticleIndex;                      // 0x2A4
    INT ActiveParticles;                    // 0x2A8
    FLOAT PPSFraction;                      // 0x2AC
    FBox BoundingBox;                       // 0x2B0
    FBox LocalBoundingBox;                  // 0x2CC
    BITFIELD bUsePrecomputedBoundingBox:1;  // 0x2E8
    FBox PrecomputedBoundingBox;            // 0x2EC
    FVector RealExtentMultiplier;           // 0x308
    BITFIELD RealDisableFogging:1;          // 0x314
    BITFIELD AllParticlesDead:1;
    BITFIELD WarmedUp:1;
    BITFIELD TickedInGame:1;
    INT OtherIndex;                         // 0x318
    FLOAT InitialDelay;                     // 0x31C
    FVector GlobalOffset;                   // 0x320
};
T3_CHECK_SIZE(UParticleEmitter, 0x32C);

class UBeamEmitter : public UParticleEmitter
{
    DECLARE_CLASS(UBeamEmitter, UParticleEmitter, 0x0, Engine)

public:
    virtual ~UBeamEmitter();                // slot 2: 0x109ACB30
    virtual void Unknown40();               // slot 16: 0x109AA300

public:
    FRange BeamDistanceRange;               // 0x32C
    TArray<FParticleBeamEndPoint> BeamEndPoints; // 0x334
    BYTE DetermineEndPointBy;               // 0x340  EBeamEndPointType
    FLOAT BeamTextureUScale;                // 0x344
    FLOAT BeamTextureVScale;                // 0x348
    INT RotatingSheets;                     // 0x34C
    FRangeVector LowFrequencyNoiseRange;    // 0x350
    INT LowFrequencyPoints;                 // 0x368
    FRangeVector HighFrequencyNoiseRange;   // 0x36C
    INT HighFrequencyPoints;                // 0x384
    TArray<FParticleBeamScale> LFScaleFactors; // 0x388
    TArray<FParticleBeamScale> HFScaleFactors; // 0x394
    FLOAT LFScaleRepeats;                   // 0x3A0
    FLOAT HFScaleRepeats;                   // 0x3A4
    BITFIELD UseHighFrequencyScale:1;       // 0x3A8
    BITFIELD UseLowFrequencyScale:1;
    BITFIELD NoiseDeterminesEndPoint:1;
    BITFIELD UseBranching:1;
    BITFIELD LinkupLifetime:1;
    BITFIELD SplineLowFrequencyPoints:1;
    BITFIELD ForceStayAttachedToOwner:1;
    BITFIELD CollapseOffsetTowardEmitter:1;
    FLOAT DelayTimeBeforeCollapse;          // 0x3AC
    FLOAT CollapseVelocity;                 // 0x3B0
    FRange BranchProbability;               // 0x3B4
    INT BranchEmitter;                      // 0x3BC
    FRange BranchSpawnAmountRange;          // 0x3C0
    INT SheetsUsed;                         // 0x3C8
    INT VerticesPerParticle;                // 0x3CC
    INT IndicesPerParticle;                 // 0x3D0
    INT PrimitivesPerParticle;              // 0x3D4
    FLOAT BeamValueSum;                     // 0x3D8
    TArray<FParticleBeamData> HFPoints;     // 0x3DC
    TArray<FVector> LFPoints;               // 0x3E8
    TArray<AActor*> HitActors;              // 0x3F4
    TArray<FString> Hardpoints;             // 0x400
    FLOAT CurrentDelayTimeBeforeCollapse;   // 0x40C
    FLOAT DistanceOffsetHasMovedSoFar;      // 0x410
};
T3_CHECK_SIZE(UBeamEmitter, 0x414);

class UBitmap : public UObject
{
    DECLARE_CLASS(UBitmap, UObject, 0x1, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x1096D7A0
    virtual ~UBitmap();                     // slot 2: 0x1096BE40
    virtual void PostLoad();                // slot 7: 0x1096BC10
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x1096BA90

public:
    BYTE Format;                            // 0x2C  ETextureFormat
    UPalette* Palette;                      // 0x30
    BYTE UBits;                             // 0x34
    BYTE VBits;                             // 0x35
    INT USize;                              // 0x38
    INT VSize;                              // 0x3C
    INT UClamp;                             // 0x40
    INT VClamp;                             // 0x44
    FColor MipZero;                         // 0x48
    FColor MaxColor;                        // 0x4C
    INT InternalTime[2];                    // 0x50
};
T3_CHECK_SIZE(UBitmap, 0x58);

class UBotDominationLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UBotDominationLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UBotDominationLinkDataObject();// slot 2: 0x1099F870

public:
};
T3_CHECK_SIZE(UBotDominationLinkDataObject, 0x50);

class UBreakingBeamLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UBreakingBeamLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UBreakingBeamLinkDataObject(); // slot 2: 0x1099F900

public:
};
T3_CHECK_SIZE(UBreakingBeamLinkDataObject, 0x50);

class UCARDEntry : public UObject
{
    DECLARE_CLASS(UCARDEntry, UObject, 0x40, Engine)

public:
    virtual ~UCARDEntry();                  // slot 2: 0x1098AA70
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x1098ABF0

public:
    BYTE Pad2C[0x34];
};
T3_CHECK_SIZE(UCARDEntry, 0x60);

class UCanvas : public UObject
{
    DECLARE_CLASS(UCanvas, UObject, 0x8, Engine)

public:
    virtual ~UCanvas();                     // slot 2: 0x109D1A10

public:
    UFont* Font;                            // 0x2C
    FLOAT SpaceX;                           // 0x30
    FLOAT SpaceY;                           // 0x34
    FLOAT OrgX;                             // 0x38
    FLOAT OrgY;                             // 0x3C
    FLOAT ClipX;                            // 0x40
    FLOAT ClipY;                            // 0x44
    FLOAT CurX;                             // 0x48
    FLOAT CurY;                             // 0x4C
    FLOAT Z;                                // 0x50
    BYTE Style;                             // 0x54
    FLOAT CurYL;                            // 0x58
    FColor DrawColor;                       // 0x5C
    BITFIELD bCenter:1;                     // 0x60
    BITFIELD bNoSmooth:1;
    INT SizeX;                              // 0x64
    INT SizeY;                              // 0x68
    UFont* SmallFont;                       // 0x6C
    UFont* MedFont;                         // 0x70
    UFont* XBoxFont;                        // 0x74
    UViewport* Viewport;                    // 0x78
};
T3_CHECK_SIZE(UCanvas, 0x7C);

class UCinematicLightLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UCinematicLightLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UCinematicLightLinkDataObject();// slot 2: 0x1099F990

public:
};
T3_CHECK_SIZE(UCinematicLightLinkDataObject, 0x50);

class UHardpointLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UHardpointLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UHardpointLinkDataObject();    // slot 2: 0x1099FFC0

public:
    FStringNoInit m_parentBone;             // 0x50
};
T3_CHECK_SIZE(UHardpointLinkDataObject, 0x5C);

class USpawnableHardpointLinkDataObject : public UHardpointLinkDataObject
{
    DECLARE_CLASS(USpawnableHardpointLinkDataObject, UHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~USpawnableHardpointLinkDataObject();// slot 2: 0x109A0370

public:
    INT NumberToSpawn;                      // 0x5C
    BITFIELD bTakeParentRotation:1;         // 0x60
    BITFIELD bAttachObjects:1;
    BITFIELD bDeleteOnDeath:1;
    FStringNoInit m_childBone;              // 0x64
};
T3_CHECK_SIZE(USpawnableHardpointLinkDataObject, 0x70);

class UCollisionSpawnLinkDataObject : public USpawnableHardpointLinkDataObject
{
    DECLARE_CLASS(UCollisionSpawnLinkDataObject, USpawnableHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~UCollisionSpawnLinkDataObject();// slot 2: 0x109A03E0

public:
    BITFIELD Active:1;                      // 0x70
    FStringNoInit Tag;                      // 0x74
};
T3_CHECK_SIZE(UCollisionSpawnLinkDataObject, 0x80);

class UCreationSpawnLinkDataObject : public UHardpointLinkDataObject
{
    DECLARE_CLASS(UCreationSpawnLinkDataObject, UHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~UCreationSpawnLinkDataObject();// slot 2: 0x109A0030

public:
    INT m_numberToSpawn;                    // 0x5C
};
T3_CHECK_SIZE(UCreationSpawnLinkDataObject, 0x60);

class UTexture : public UBitmap
{
    DECLARE_CLASS(UTexture, UBitmap, 0x40, Engine)

public:
    UTexture* BumpMap;                      // 0x58
    UTexture* DetailTexture;                // 0x5C
    UTexture* MacroTexture;                 // 0x60
    UTexture* EnvironmentMap;               // 0x64
    BYTE EnvMapTransformType;               // 0x68  EEnvMapTransformType
    BYTE UClampMode;                        // 0x69  ETexClampMode
    BYTE VClampMode;                        // 0x6A  ETexClampMode
    FLOAT Diffuse;                          // 0x6C
    FLOAT Specular;                         // 0x70
    FLOAT Alpha;                            // 0x74
    FLOAT DrawScale;                        // 0x78
    FLOAT Friction;                         // 0x7C
    FLOAT MipMult;                          // 0x80
    BITFIELD bInvisible:1;                  // 0x84
    BITFIELD bMasked:1;
    BITFIELD bTransparent:1;
    BITFIELD bNotSolid:1;
    BITFIELD bEnvironment:1;
    BITFIELD bSemisolid:1;
    BITFIELD bModulate:1;
    BITFIELD bFakeBackdrop:1;
    BITFIELD bTwoSided:1;
    BITFIELD bAutoUPan:1;
    BITFIELD bAutoVPan:1;
    BITFIELD bNoSmooth:1;
    BITFIELD bAlphaTexture:1;
    BITFIELD bSmallWavy:1;
    BITFIELD bWaterWavy:1;
    BITFIELD bUseDiffuseAlpha:1;
    BITFIELD bNoMerge:1;
    BITFIELD bCloudWavy:1;
    BITFIELD bDirtyShadows:1;
    BITFIELD bHighLedge:1;
    BITFIELD bSpecialLit:1;
    BITFIELD bGouraud:1;
    BITFIELD bUnlit:1;
    BITFIELD bHighShadowDetail:1;
    BITFIELD bPortal:1;
    BITFIELD bMirrored:1;
    BITFIELD bX2:1;
    BITFIELD bX3:1;
    BITFIELD bX4:1;
    BITFIELD bX5:1;
    BITFIELD bX6:1;
    BITFIELD bX7:1;
    BITFIELD bHighColorQuality:1;           // 0x88
    BITFIELD bHighTextureQuality:1;
    BITFIELD bCanClimb:1;
    BITFIELD bArrowStick:1;
    BITFIELD bRealtime:1;
    BITFIELD bParametric:1;
    BITFIELD bRealtimeChanged:1;
    BITFIELD bHasComp:1;
    BYTE LODSet;                            // 0x8C  ELODSet
    UTexture* AnimNext;                     // 0x90
    UTexture* AnimCurrent;                  // 0x94
    BYTE PrimeCount;                        // 0x98
    BYTE PrimeCurrent;                      // 0x99
    FLOAT MinFrameRate;                     // 0x9C
    FLOAT MaxFrameRate;                     // 0xA0
    FLOAT Accumulator;                      // 0xA4
    TArray<INT> Mips;                       // 0xA8
    BYTE CompFormat;                        // 0xB4  ETextureFormat
    INT RenderInterface[5];                 // 0xB8
    FLOAT DiffuseColor[4];                  // 0xCC
};
T3_CHECK_SIZE(UTexture, 0xDC);

class UCubemap : public UTexture
{
    DECLARE_CLASS(UCubemap, UTexture, 0x40, Engine)

public:
    virtual ~UCubemap();                    // slot 2: 0x1096BFA0

public:
    UTexture* Faces[6];                     // 0xDC
    INT CubemapRenderInterface[5];          // 0xF4
};
T3_CHECK_SIZE(UCubemap, 0x108);

class UDeathSpawnLinkDataObject : public UHardpointLinkDataObject
{
    DECLARE_CLASS(UDeathSpawnLinkDataObject, UHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~UDeathSpawnLinkDataObject();   // slot 2: 0x109A00F0

public:
    INT m_numberToSpawn;                    // 0x5C
    INT m_stimulusTrigger;                  // 0x60
    BITFIELD m_bTakeParentRotation:1;       // 0x64
};
T3_CHECK_SIZE(UDeathSpawnLinkDataObject, 0x68);

class UDelaySpawnLinkDataObject : public USpawnableHardpointLinkDataObject
{
    DECLARE_CLASS(UDelaySpawnLinkDataObject, USpawnableHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~UDelaySpawnLinkDataObject();   // slot 2: 0x109A0490

public:
};
T3_CHECK_SIZE(UDelaySpawnLinkDataObject, 0x70);

class UDestroyOnDeathLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UDestroyOnDeathLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UDestroyOnDeathLinkDataObject();// slot 2: 0x1099FA20

public:
};
T3_CHECK_SIZE(UDestroyOnDeathLinkDataObject, 0x50);

class UDoorLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UDoorLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UDoorLinkDataObject();         // slot 2: 0x1099FAB0

public:
};
T3_CHECK_SIZE(UDoorLinkDataObject, 0x50);

class UDynamicBeamEmitter : public UBeamEmitter
{
    DECLARE_CLASS(UDynamicBeamEmitter, UBeamEmitter, 0x0, Engine)

public:
    virtual ~UDynamicBeamEmitter();         // slot 2: 0x109ADD10

public:
    TArray<FVector> DynamicPointList;       // 0x414
    BITFIELD UseDynamicPoints:1;            // 0x420
};
T3_CHECK_SIZE(UDynamicBeamEmitter, 0x424);

class UElevatorFloorMarkerLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UElevatorFloorMarkerLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UElevatorFloorMarkerLinkDataObject();// slot 2: 0x1099FBD0

public:
};
T3_CHECK_SIZE(UElevatorFloorMarkerLinkDataObject, 0x50);

class UElevatorLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UElevatorLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UElevatorLinkDataObject();     // slot 2: 0x1099FC60

public:
};
T3_CHECK_SIZE(UElevatorLinkDataObject, 0x50);

class UEngine : public USubsystem
{
    DECLARE_CLASS(UEngine, USubsystem, 0xD, Engine)
    void StaticConstructor();       // 0x10977B10

public:
    UClass* Language;                       // 0x30
    UPrimitive* Cylinder;                   // 0x34
    UClient* Client;                        // 0x38
    UAISubsystem* AI;                       // 0x3C
    UPhysicsSubsystem* Physics;             // 0x40
    UGameSubsystem* Game;                   // 0x44
    URenderDevice* GRenDev;                 // 0x48
    INT TickCycles;                         // 0x4C
    INT GameCycles;                         // 0x50
    INT ClientCycles;                       // 0x54
    INT CacheSizeMegs;                      // 0x58
    BITFIELD UseSound:1;                    // 0x5C
    FLOAT CurrentTickRate;                  // 0x60
    INT ProfileDisplayMode;                 // 0x64
    INT ProfileDetailDisplayMode;           // 0x68
    INT ProfileSelectedGroups;              // 0x6C
    INT ProfileSelectedStatsCategory;       // 0x70
    INT ProfileDisplayInstance;             // 0x74
    INT ProfileFrameTimeHistory;            // 0x78
    INT ProfileFrameTimeIndex;              // 0x7C
    FColor C_WorldBox;                      // 0x80
    FColor C_GroundPlane;                   // 0x84
    FColor C_GroundHighlight;               // 0x88
    FColor C_BrushWire;                     // 0x8C
    FColor C_Pivot;                         // 0x90
    FColor C_Select;                        // 0x94
    FColor C_Current;                       // 0x98
    FColor C_AddWire;                       // 0x9C
    FColor C_SubtractWire;                  // 0xA0
    FColor C_GreyWire;                      // 0xA4
    FColor C_BrushVertex;                   // 0xA8
    FColor C_BrushSnap;                     // 0xAC
    FColor C_Invalid;                       // 0xB0
    FColor C_ActorWire;                     // 0xB4
    FColor C_ActorHiWire;                   // 0xB8
    FColor C_Black;                         // 0xBC
    FColor C_White;                         // 0xC0
    FColor C_Mask;                          // 0xC4
    FColor C_SemiSolidWire;                 // 0xC8
    FColor C_NonSolidWire;                  // 0xCC
    FColor C_WireBackground;                // 0xD0
    FColor C_WireGridAxis;                  // 0xD4
    FColor C_ActorArrow;                    // 0xD8
    FColor C_ScaleBox;                      // 0xDC
    FColor C_ScaleBoxHi;                    // 0xE0
    FColor C_ZoneWire;                      // 0xE4
    FColor C_Mover;                         // 0xE8
    FColor C_OrthoBackground;               // 0xEC
    FColor C_StaticMesh;                    // 0xF0
    FColor C_VolumeBrush;                   // 0xF4
    INT GameStats[5];                       // 0xF8
};
T3_CHECK_SIZE(UEngine, 0x10C);

class UFillLightLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UFillLightLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UFillLightLinkDataObject();    // slot 2: 0x1099FCF0

public:
};
T3_CHECK_SIZE(UFillLightLinkDataObject, 0x50);

class UFireEffectLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UFireEffectLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UFireEffectLinkDataObject();   // slot 2: 0x1099FD80

public:
};
T3_CHECK_SIZE(UFireEffectLinkDataObject, 0x50);

class UFlinderizeLinkDataObject : public UHardpointLinkDataObject
{
    DECLARE_CLASS(UFlinderizeLinkDataObject, UHardpointLinkDataObject, 0x0, Engine)

public:
    virtual ~UFlinderizeLinkDataObject();   // slot 2: 0x109A0200

public:
    INT m_numberToSpawn;                    // 0x5C
    FLOAT m_ConeTheta;                      // 0x60
    BYTE m_spreadPattern;                   // 0x64  eSpreadPattern
};
T3_CHECK_SIZE(UFlinderizeLinkDataObject, 0x68);

class UFragRoundLinkDataObject : public UFlinderizeLinkDataObject
{
    DECLARE_CLASS(UFragRoundLinkDataObject, UFlinderizeLinkDataObject, 0x0, Engine)

public:
    virtual ~UFragRoundLinkDataObject();    // slot 2: 0x109A0240

public:
};
T3_CHECK_SIZE(UFragRoundLinkDataObject, 0x68);

class UFrobEventLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UFrobEventLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UFrobEventLinkDataObject();    // slot 2: 0x1099FE10

public:
};
T3_CHECK_SIZE(UFrobEventLinkDataObject, 0x50);

class UFrobLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UFrobLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UFrobLinkDataObject();         // slot 2: 0x1099FEA0

public:
};
T3_CHECK_SIZE(UFrobLinkDataObject, 0x50);

class UGameEngine : public UEngine
{
    DECLARE_CLASS(UGameEngine, UEngine, 0xC, Engine)
    void StaticConstructor();       // 0x10983590

public:
    ULevel* GLevel;                         // 0x10C
    ULevel* GEntry;                         // 0x110
    FURL LastURL;                           // 0x114
    TArray<FString> ServerActors;           // 0x158
    TArray<FString> ServerPackages;         // 0x164
    TArray<FString> EnginePackages;         // 0x170
};
T3_CHECK_SIZE(UGameEngine, 0x17C);

class UPhysicsSubsystem : public USubsystem
{
    DECLARE_CLASS(UPhysicsSubsystem, USubsystem, 0xD, Engine)

public:
    BYTE Pad30[0x8];
};
T3_CHECK_SIZE(UPhysicsSubsystem, 0x38);

class UGameSubsystem : public USubsystem
{
    DECLARE_CLASS(UGameSubsystem, USubsystem, 0xD, Engine)

public:
    BYTE Pad30[0x4];
};
T3_CHECK_SIZE(UGameSubsystem, 0x34);

class UHighlightEventLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UHighlightEventLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UHighlightEventLinkDataObject();// slot 2: 0x109A0520

public:
};
T3_CHECK_SIZE(UHighlightEventLinkDataObject, 0x50);

class UHingedAttachmentLinkDataObject : public UAttachmentLinkDataObject
{
    DECLARE_CLASS(UHingedAttachmentLinkDataObject, UAttachmentLinkDataObject, 0x0, Engine)

public:
    virtual ~UHingedAttachmentLinkDataObject();// slot 2: 0x1099F560

public:
    FVector m_hingeLocation;                // 0x74
    FVector m_hingeAxis;                    // 0x80
    FLOAT m_hingeLimitMin;                  // 0x8C
    FLOAT m_hingeLimitMax;                  // 0x90
    FLOAT m_hingeFriction;                  // 0x94
    FVector m_pivotInA;                     // 0x98
    FVector m_pivotInB;                     // 0xA4
    FVector m_axleInA;                      // 0xB0
    FVector m_axleInB;                      // 0xBC
    FVector m_perpToAxleInA1;               // 0xC8
    FVector m_perpToAxleInA2;               // 0xD4
    FVector m_perpToFreeAxisInB;            // 0xE0
    FLOAT m_maxFrictionTorque;              // 0xEC
    FLOAT m_lastAngle;                      // 0xF0
    FLOAT m_rotations;                      // 0xF4
    BITFIELD m_motorActive:1;               // 0xF8
    BITFIELD m_containsSaveData:1;
};
T3_CHECK_SIZE(UHingedAttachmentLinkDataObject, 0xFC);

class UHitSpangLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UHitSpangLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UHitSpangLinkDataObject();     // slot 2: 0x109A05B0

public:
};
T3_CHECK_SIZE(UHitSpangLinkDataObject, 0x50);

class UInterestLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UInterestLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UInterestLinkDataObject();     // slot 2: 0x109A0640

public:
};
T3_CHECK_SIZE(UInterestLinkDataObject, 0x50);

class ULightLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(ULightLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~ULightLinkDataObject();        // slot 2: 0x109A06D0

public:
};
T3_CHECK_SIZE(ULightLinkDataObject, 0x50);

class ULoadoutLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(ULoadoutLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~ULoadoutLinkDataObject();      // slot 2: 0x109A07A0

public:
    FStringNoInit m_parentBone;             // 0x50
    FStringNoInit m_childBone;              // 0x5C
    BITFIELD bIsWeaponAttachment:1;         // 0x68
};
T3_CHECK_SIZE(ULoadoutLinkDataObject, 0x6C);

class ULockAssociationLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(ULockAssociationLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~ULockAssociationLinkDataObject();// slot 2: 0x109A0850

public:
};
T3_CHECK_SIZE(ULockAssociationLinkDataObject, 0x50);

class UMatSubAction : public UMatObject
{
    DECLARE_CLASS(UMatSubAction, UMatObject, 0x0, Engine)

public:
    virtual ~UMatSubAction();               // slot 2: 0x10997EC0
    virtual void Unknown3C();               // slot 15: 0x1099AAF0

public:
    FLOAT Delay;                            // 0x2C
    FLOAT Duration;                         // 0x30
    UTexture* Icon;                         // 0x34
    BYTE Status;                            // 0x38  ESAStatus
    FStringNoInit Desc;                     // 0x3C
    FLOAT PctStarting;                      // 0x48
    FLOAT PctEnding;                        // 0x4C
    FLOAT PctDuration;                      // 0x50
};
T3_CHECK_SIZE(UMatSubAction, 0x54);

class UMeshEmitter : public UParticleEmitter
{
    DECLARE_CLASS(UMeshEmitter, UParticleEmitter, 0x0, Engine)

public:
    virtual ~UMeshEmitter();                // slot 2: 0x109AE530
    virtual void Unknown3C();               // slot 15: 0x109AF360

public:
    UStaticMesh* StaticMesh;                // 0x32C
    BITFIELD UseMeshBlendMode:1;            // 0x330
    BITFIELD RenderTwoSided:1;
    FVector MeshExtent;                     // 0x334
};
T3_CHECK_SIZE(UMeshEmitter, 0x340);

class UMovementModeLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UMovementModeLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UMovementModeLinkDataObject(); // slot 2: 0x109A08E0

public:
};
T3_CHECK_SIZE(UMovementModeLinkDataObject, 0x50);

class UOwnershipLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UOwnershipLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UOwnershipLinkDataObject();    // slot 2: 0x109A0970

public:
};
T3_CHECK_SIZE(UOwnershipLinkDataObject, 0x50);

class UPalette : public UObject
{
    DECLARE_CLASS(UPalette, UObject, 0x40, Engine)

public:
    virtual ~UPalette();                    // slot 2: 0x1096B290
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x1096AED0

public:
    TArray<FColor> Colors;                  // 0x2C
};
T3_CHECK_SIZE(UPalette, 0x38);

class UPlayer : public UObject
{
    DECLARE_CLASS(UPlayer, UObject, 0xD, Engine)

public:
    virtual void Destroy();                 // slot 0: 0x10C86020
    virtual ~UPlayer();                     // slot 2: 0x10C8DA60
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x109DCFF0
    virtual void PostEditChange();          // slot 14: 0x10C85D10

public:
    INT vfOut;                              // 0x2C
    INT vfExec;                             // 0x30
    APlayerController* Actor;               // 0x34
    BITFIELD bWindowsMouseAvailable:1;      // 0x38
    BITFIELD bShowWindowsMouse:1;
    BITFIELD bSuspendPrecaching:1;
    FLOAT WindowsMouseX;                    // 0x3C
    FLOAT WindowsMouseY;                    // 0x40
    INT CurrentNetSpeed;                    // 0x44
    INT ConfiguredInternetSpeed;            // 0x48
    INT ConfiguredLanSpeed;                 // 0x4C
    BYTE SelectedCursor;                    // 0x50
};
T3_CHECK_SIZE(UPlayer, 0x54);

class UPlayerSetupInfoLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UPlayerSetupInfoLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UPlayerSetupInfoLinkDataObject();// slot 2: 0x109A0A00

public:
};
T3_CHECK_SIZE(UPlayerSetupInfoLinkDataObject, 0x50);

class UPointAttachmentLinkDataObject : public UAttachmentLinkDataObject
{
    DECLARE_CLASS(UPointAttachmentLinkDataObject, UAttachmentLinkDataObject, 0x0, Engine)

public:
    virtual ~UPointAttachmentLinkDataObject();// slot 2: 0x1099F600

public:
    FVector m_pointOffset;                  // 0x74
    FLOAT m_pointLimitMin;                  // 0x80
    FLOAT m_pointLimitMax;                  // 0x84
};
T3_CHECK_SIZE(UPointAttachmentLinkDataObject, 0x88);

class UPowerLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UPowerLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UPowerLinkDataObject();        // slot 2: 0x109A0A90

public:
};
T3_CHECK_SIZE(UPowerLinkDataObject, 0x50);

class UProjectileLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UProjectileLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UProjectileLinkDataObject();   // slot 2: 0x109A0B20

public:
    BITFIELD IsAltFire:1;                   // 0x50
};
T3_CHECK_SIZE(UProjectileLinkDataObject, 0x54);

class UPuddleConnectorLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UPuddleConnectorLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UPuddleConnectorLinkDataObject();// slot 2: 0x109A0BB0

public:
};
T3_CHECK_SIZE(UPuddleConnectorLinkDataObject, 0x50);

class UPuddleMarkLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UPuddleMarkLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UPuddleMarkLinkDataObject();   // slot 2: 0x109A0C40

public:
};
T3_CHECK_SIZE(UPuddleMarkLinkDataObject, 0x50);

class UReferenceLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UReferenceLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UReferenceLinkDataObject();    // slot 2: 0x109A0CD0

public:
};
T3_CHECK_SIZE(UReferenceLinkDataObject, 0x50);

class URigidAttachmentLinkDataObject : public UAttachmentLinkDataObject
{
    DECLARE_CLASS(URigidAttachmentLinkDataObject, UAttachmentLinkDataObject, 0x0, Engine)

public:
    virtual ~URigidAttachmentLinkDataObject();// slot 2: 0x1099F6A0

public:
    BITFIELD bDontSpawn:1;                  // 0x74
    BITFIELD bDeleteChildOnDeath:1;
    BITFIELD m_bConcretes:1;
    BITFIELD m_bRepositionAfterRotation:1;
    BITFIELD bDontPropogateHiddenFlagToChild:1;
    FRotator m_rotationOffset;              // 0x78
    FVector m_translationOffset;            // 0x84
    INT m_pAttachmentUpdateCallback;        // 0x90
};
T3_CHECK_SIZE(URigidAttachmentLinkDataObject, 0x94);

class URuntimeAttachmentLinkDataObject : public UAttachmentLinkDataObject
{
    DECLARE_CLASS(URuntimeAttachmentLinkDataObject, UAttachmentLinkDataObject, 0x0, Engine)

public:
    virtual ~URuntimeAttachmentLinkDataObject();// slot 2: 0x1099F740

public:
    BITFIELD bDeleteChildOnDeath:1;         // 0x74
};
T3_CHECK_SIZE(URuntimeAttachmentLinkDataObject, 0x78);

class URuntimeFireEffectLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(URuntimeFireEffectLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~URuntimeFireEffectLinkDataObject();// slot 2: 0x109A0D60

public:
};
T3_CHECK_SIZE(URuntimeFireEffectLinkDataObject, 0x50);

class USittingLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USittingLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~USittingLinkDataObject();      // slot 2: 0x109A0DF0

public:
};
T3_CHECK_SIZE(USittingLinkDataObject, 0x50);

class USkeletalFireEffectLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USkeletalFireEffectLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~USkeletalFireEffectLinkDataObject();// slot 2: 0x109A0EB0

public:
    FStringNoInit m_parentBone;             // 0x50
};
T3_CHECK_SIZE(USkeletalFireEffectLinkDataObject, 0x5C);

class USleepingLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USleepingLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~USleepingLinkDataObject();     // slot 2: 0x109A0F50

public:
};
T3_CHECK_SIZE(USleepingLinkDataObject, 0x50);

class USlidingAttachmentLinkDataObject : public UAttachmentLinkDataObject
{
    DECLARE_CLASS(USlidingAttachmentLinkDataObject, UAttachmentLinkDataObject, 0x0, Engine)

public:
    virtual ~USlidingAttachmentLinkDataObject();// slot 2: 0x1099F7D0

public:
    FVector m_slideAxis;                    // 0x74
    FLOAT m_slideFriction;                  // 0x80
    FLOAT m_lip;                            // 0x84
    FVector m_pivotInA;                     // 0x88
    FVector m_pivotInB;                     // 0x94
    FVector m_shaftInA;                     // 0xA0
    FVector m_shaftInB;                     // 0xAC
    FVector m_perpToShaftInB1;              // 0xB8
    FVector m_perpToShaftInB2;              // 0xC4
    FRotator m_BtoAoffsetRotation;          // 0xD0
    FLOAT m_minLimit;                       // 0xDC
    FLOAT m_maxLimit;                       // 0xE0
    FLOAT m_maxFrictionForce;               // 0xE4
    BITFIELD m_containsSaveData:1;          // 0xE8
};
T3_CHECK_SIZE(USlidingAttachmentLinkDataObject, 0xEC);

class USparkEmitter : public UParticleEmitter
{
    DECLARE_CLASS(USparkEmitter, UParticleEmitter, 0x0, Engine)

public:
    virtual ~USparkEmitter();               // slot 2: 0x109AEB60
    virtual void Unknown3C();               // slot 15: 0x109AF360

public:
    FRange LineSegmentsRange;               // 0x32C
    FRange TimeBeforeVisibleRange;          // 0x334
    FRange TimeBetweenSegmentsRange;        // 0x33C
    TArray<FParticleSparkData> SparkData;   // 0x344
    UVertexBuffer* VertexBuffer;            // 0x350
    UIndexBuffer* IndexBuffer;              // 0x354
    INT NumSegments;                        // 0x358
    INT VerticesPerParticle;                // 0x35C
    INT IndicesPerParticle;                 // 0x360
    INT PrimitivesPerParticle;              // 0x364
};
T3_CHECK_SIZE(USparkEmitter, 0x368);

class USpawnLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USpawnLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~USpawnLinkDataObject();        // slot 2: 0x109A0FE0

public:
};
T3_CHECK_SIZE(USpawnLinkDataObject, 0x50);

class USpriteEmitter : public UParticleEmitter
{
    DECLARE_CLASS(USpriteEmitter, UParticleEmitter, 0x0, Engine)

public:
    BYTE UseDirectionAs;                    // 0x32C  EParticleDirectionUsage
    FVector ProjectionNormal;               // 0x330
    FVector RealProjectionNormal;           // 0x33C
    BITFIELD SortParticles:1;               // 0x348
    BITFIELD UseTrailing:1;
    FRange TrailersPerSecond;               // 0x34C
    INT TrailEmitter;                       // 0x354
    BYTE TrailLifetime;                     // 0x358  EParticleTrailingLifetime
    FLOAT PullDistance;                     // 0x35C
};
T3_CHECK_SIZE(USpriteEmitter, 0x360);

class UStimulusModifierLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UStimulusModifierLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UStimulusModifierLinkDataObject();// slot 2: 0x109A1070

public:
};
T3_CHECK_SIZE(UStimulusModifierLinkDataObject, 0x50);

class USubActionFOV : public UMatSubAction
{
    DECLARE_CLASS(USubActionFOV, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionFOV();               // slot 2: 0x10998040

public:
    FRange FOV;                             // 0x54
};
T3_CHECK_SIZE(USubActionFOV, 0x5C);

class USubActionFade : public UMatSubAction
{
    DECLARE_CLASS(USubActionFade, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionFade();              // slot 2: 0x10997F80

public:
    FColor FadeColor;                       // 0x54
    BITFIELD bFadeOut:1;                    // 0x58
};
T3_CHECK_SIZE(USubActionFade, 0x5C);

class USubActionGameSpeed : public UMatSubAction
{
    DECLARE_CLASS(USubActionGameSpeed, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionGameSpeed();         // slot 2: 0x10998100

public:
    FRange GameSpeed;                       // 0x54
};
T3_CHECK_SIZE(USubActionGameSpeed, 0x5C);

class USubActionOrientation : public UMatSubAction
{
    DECLARE_CLASS(USubActionOrientation, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionOrientation();       // slot 2: 0x109981E0

public:
    FMatObjectOrientation CamOrientation;   // 0x54
};
T3_CHECK_SIZE(USubActionOrientation, 0x88);

class USubActionSceneSpeed : public UMatSubAction
{
    DECLARE_CLASS(USubActionSceneSpeed, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionSceneSpeed();        // slot 2: 0x109982B0

public:
    FRange SceneSpeed;                      // 0x54
};
T3_CHECK_SIZE(USubActionSceneSpeed, 0x5C);

class USubActionTrigger : public UMatSubAction
{
    DECLARE_CLASS(USubActionTrigger, UMatSubAction, 0x0, Engine)

public:
    virtual ~USubActionTrigger();           // slot 2: 0x10998370

public:
    FName EventName;                        // 0x54
};
T3_CHECK_SIZE(USubActionTrigger, 0x58);

class USwooshLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USwooshLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~USwooshLinkDataObject();       // slot 2: 0x109A1100

public:
};
T3_CHECK_SIZE(USwooshLinkDataObject, 0x50);

class UTriggerRegistrar : public UObject
{
    DECLARE_CLASS(UTriggerRegistrar, UObject, 0xD, Engine)

public:
    virtual ~UTriggerRegistrar();           // slot 2: 0x10AB3CE0
    virtual void Register();                // slot 19: 0x10ABD7D0

public:
};
T3_CHECK_SIZE(UTriggerRegistrar, 0x2C);

class UTargetLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UTargetLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UTargetLinkDataObject();       // slot 2: 0x109A1190

public:
    FVector TargetLocationOffset;           // 0x50
};
T3_CHECK_SIZE(UTargetLinkDataObject, 0x5C);

class UTriggerScriptLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UTriggerScriptLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UTriggerScriptLinkDataObject();// slot 2: 0x109A1250

public:
    FStringNoInit LinkName;                 // 0x50
};
T3_CHECK_SIZE(UTriggerScriptLinkDataObject, 0x5C);

class UUserArmImplementationLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UUserArmImplementationLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UUserArmImplementationLinkDataObject();// slot 2: 0x109A12F0

public:
};
T3_CHECK_SIZE(UUserArmImplementationLinkDataObject, 0x50);

class UUserLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UUserLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UUserLinkDataObject();         // slot 2: 0x109A1380

public:
};
T3_CHECK_SIZE(UUserLinkDataObject, 0x50);

class UVulnerabilityLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UVulnerabilityLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UVulnerabilityLinkDataObject();// slot 2: 0x109A1410

public:
};
T3_CHECK_SIZE(UVulnerabilityLinkDataObject, 0x50);

class UWaypointInterpolationLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UWaypointInterpolationLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UWaypointInterpolationLinkDataObject();// slot 2: 0x109A14A0

public:
    FLOAT Speed;                            // 0x50
};
T3_CHECK_SIZE(UWaypointInterpolationLinkDataObject, 0x54);

class UWeaponModLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UWeaponModLinkDataObject, ULinkDataObject, 0x0, Engine)

public:
    virtual ~UWeaponModLinkDataObject();    // slot 2: 0x109A1530

public:
};
T3_CHECK_SIZE(UWeaponModLinkDataObject, 0x50);

#endif
