// T3Player/T3PlayerClasses.h: the T3Player package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_T3PLAYER_T3PLAYERCLASSES_H
#define T3_T3PLAYER_T3PLAYERCLASSES_H

#include "Core/Core.h"
#include "Core/CoreClasses.h"
#include "Engine/EngineClasses.h"

class AActor;
class APawn;

enum EArmUse
{
    EAU_FREE,
    EAU_FORCED_BODY,
    EAU_FORCED_ARMS
};

enum EAttachPos
{
    EAP_BELT
};

enum EBodyMovementType
{
    ERT_Normal,
    ERT_RotateBodyOnly,
    ERT_NoMovement
};

enum EFaction
{
    EF_Hammer,
    EF_Pagan
};

enum EFatalAttackState
{
    eFAS_None,
    eFAS_ArmsPrepared,
    eFAS_BodyPrepared,
    eFAS_Attacking
};

enum GARRETT_SPEEDS
{
    GSP_SLOW,
    GSP_MEDIUM,
    GSP_FAST,
    GSP_IDLE
};

struct FRemovedInventoryInfo
{
    UClass* invClass;                       // 0x0
    INT num;                                // 0x4
};
T3_CHECK_SIZE(FRemovedInventoryInfo, 0x8);

struct FInvLootRecord
{
    FStringNoInit ItemName;                 // 0x0
    INT Quantity;                           // 0xC
    INT SellPrice;                          // 0x10
    BYTE lootType;                          // 0x14  ELootType
    BITFIELD bSpecial:1;                    // 0x18
};
T3_CHECK_SIZE(FInvLootRecord, 0x1C);

struct FInvQuestItemRecord
{
    FStringNoInit ClassName;                // 0x0
    FStringNoInit ItemName;                 // 0xC
    INT Quantity;                           // 0x18
};
T3_CHECK_SIZE(FInvQuestItemRecord, 0x1C);

struct FAnimCall
{
    FName name;                             // 0x0
    BITFIELD tween:1;                       // 0x4
    BITFIELD finish:1;
    FLOAT startPos;                         // 0x8
};
T3_CHECK_SIZE(FAnimCall, 0xC);

class AGarrett : public APlayerPawn
{
    DECLARE_CLASS(AGarrett, APlayerPawn, 0x800, T3Player)

public:
    virtual void Unknown00();               // slot 0: 0x10B21630
    virtual ~AGarrett();                    // slot 2: 0x10B133A0
    virtual void Unknown20();               // slot 8: 0x10B21AD0

public:
    TArray<FRemovedInventoryInfo> RemovedInventory; // 0x278
    FLOAT standingSpeedDef[19];             // 0x284
    FLOAT crouchingSpeedDef[19];            // 0x2D0
    AActor* curTarget;                      // 0x31C
    AActor* ladderToMount;                  // 0x320
    AActor* ropeToMount;                    // 0x324
    AActor* railToVault;                    // 0x328
    AActor* bodyCarrying;                   // 0x32C
    FLOAT ropeToMountYaw;                   // 0x330
    FLOAT ropeRotateSpeed;                  // 0x334
    FVector railToVaultNormal;              // 0x338
    INT AnimToPlay;                         // 0x344
    INT NextState;                          // 0x348
    INT MtNextState;                        // 0x34C
    FVector moveToLoc;                      // 0x350
    INT moveToYaw;                          // 0x35C
    FStringNoInit neckBoneName;             // 0x360
    INT neckBoneNumber;                     // 0x36C
    FStringNoInit rightArmBoneName;         // 0x370
    INT rightArmBoneNumber;                 // 0x37C
    FStringNoInit leftArmBoneName;          // 0x380
    INT leftArmBoneNumber;                  // 0x38C
    FStringNoInit cameraBoneName;           // 0x390
    INT cameraBoneNumber;                   // 0x39C
    FStringNoInit headingBoneName;          // 0x3A0
    INT headingBoneNumber;                  // 0x3AC
    FStringNoInit leftFootBoneName;         // 0x3B0
    INT leftFootBoneNumber;                 // 0x3BC
    FStringNoInit rightFootBoneName;        // 0x3C0
    INT rightFootBoneNumber;                // 0x3CC
    FStringNoInit pelvisBoneName;           // 0x3D0
    INT pelvisBoneNumber;                   // 0x3DC
    FStringNoInit leftHandBoneName;         // 0x3E0
    INT leftHandBoneNumber;                 // 0x3EC
    FStringNoInit rightHandBoneName;        // 0x3F0
    INT rightHandBoneNumber;                // 0x3FC
    FRotator HeadRot;                       // 0x400
    FLOAT newPitchRot;                      // 0x40C
    FLOAT newYawRot;                        // 0x410
    FLOAT jumpVel;                          // 0x414
    FLOAT mantleZ;                          // 0x418
    AActor* MantleSurface;                  // 0x41C
    FLOAT MinFallDamage;                    // 0x420
    FLOAT MaxFallDamage;                    // 0x424
    FLOAT FallDamageModifier;               // 0x428
    FLOAT MantleMinHeight;                  // 0x42C
    FLOAT MantleMaxHeight;                  // 0x430
    FLOAT MantleMinHeightJump;              // 0x434
    FLOAT StandingCollisionHeight;          // 0x438
    FLOAT StandingCollisionRadius;          // 0x43C
    AActor* WeaponHolding;                  // 0x440
    AActor* ArrowHolding;                   // 0x444
    AActor* WeaponToHold;                   // 0x448
    INT WeaponStanceTypeHolding;            // 0x44C
    BITFIELD bInBowDraw:1;                  // 0x450
    BITFIELD isCrouching:1;
    BITFIELD CanDoItemSearch:1;
    BITFIELD CanUseItems:1;
    BITFIELD bUpdatePhysHeight:1;
    BITFIELD bCrouchAfterMantle:1;
    BITFIELD bIsCameraInFirstPersonForTravel:1;
    FLOAT LastTickTime;                     // 0x454
    AActor* ObjectToLockPick;               // 0x458
    AActor* LockHandleToMove;               // 0x45C
    APawn* AIToAttack;                      // 0x460
    INT CameraMode;                         // 0x464
    FRotator CameraRotation;                // 0x468
    INT playerGold;                         // 0x474
    TArray<FInvLootRecord> playerLootList;  // 0x478
    TArray<FInvQuestItemRecord> playerQuestItemsList; // 0x484
    BITFIELD bIn3rdPersonMode:1;            // 0x490
    BITFIELD bLeftFootDown:1;
    FLOAT fidgetDelayTime;                  // 0x494
    FLOAT fidgetCycleTime;                  // 0x498
    FLOAT fidgetCycleRandom;                // 0x49C
    FLOAT backwardsTranslationScale;        // 0x4A0
    AActor* ObjectToThrow;                  // 0x4A4
    FLOAT throwVel;                         // 0x4A8
    FLOAT MinThrowForce;                    // 0x4AC
    FLOAT MaxThrowForce;                    // 0x4B0
    FLOAT maxFrobAngleCos;                  // 0x4B4
    FLOAT maxFrobAngleCos_3P;               // 0x4B8
    AActor* closestAIInRange;               // 0x4BC
    AActor* closestHostileAI;               // 0x4C0
    FVector distanceToClosestHostileAI;     // 0x4C4
    BITFIELD bInPublicSpace:1;              // 0x4D0
    BITFIELD bIsInCitySection:1;
    BITFIELD bNoiseEnabled:1;
    FLOAT movementStickXValue;              // 0x4D4
    FLOAT movementStickYValue;              // 0x4D8
    FLOAT physicsSpeed;                     // 0x4DC
    FLOAT wallFlattenedLightModifier;       // 0x4E0
    TArray<FLOAT> firstPersonMantleTable;   // 0x4E4
    TArray<FLOAT> thirdPersonMantleTable;   // 0x4F0
    FLOAT firstPersonMaxMantleHeight;       // 0x4FC
    FLOAT thirdPersonMaxMantleHeight;       // 0x500
    FStringNoInit hammerFactionActions[3];  // 0x504
    FStringNoInit paganFactionActions[3];   // 0x528
    BYTE InputSpeed;                        // 0x54C  GARRETT_SPEEDS
    BYTE ArmUse;                            // 0x54D  EArmUse
    BYTE BodyMovementType;                  // 0x54E  EBodyMovementType
    BYTE Faction;                           // 0x54F  EFaction
    BYTE FatalAttackState;                  // 0x550  EFatalAttackState
    FAnimCall GAnimCall;                    // 0x554
};
T3_CHECK_SIZE(AGarrett, 0x560);

class AT3PlayerController : public APlayerController
{
    DECLARE_CLASS(AT3PlayerController, APlayerController, 0x4, T3Player)

public:
    virtual ~AT3PlayerController();         // slot 2: 0x10B121C0

public:
    BITFIELD bIsActive:1;                   // 0x2C0
    INT pad0;                               // 0x2C4
};
T3_CHECK_SIZE(AT3PlayerController, 0x2C8);

class UAttachment_LinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UAttachment_LinkDataObject, ULinkDataObject, 0x0, T3Player)

public:
    virtual ~UAttachment_LinkDataObject();  // slot 2: 0x10B129F0

public:
    BYTE AttachPos;                         // 0x50  EAttachPos
};
T3_CHECK_SIZE(UAttachment_LinkDataObject, 0x54);

class UGarrettEquipLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UGarrettEquipLinkDataObject, ULinkDataObject, 0x0, T3Player)

public:
    virtual ~UGarrettEquipLinkDataObject(); // slot 2: 0x10B12AB0

public:
    FStringNoInit GarEquipName;             // 0x50
};
T3_CHECK_SIZE(UGarrettEquipLinkDataObject, 0x5C);

class UHUDRenderLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UHUDRenderLinkDataObject, ULinkDataObject, 0x0, T3Player)

public:
    virtual ~UHUDRenderLinkDataObject();    // slot 2: 0x10B12B50

public:
};
T3_CHECK_SIZE(UHUDRenderLinkDataObject, 0x50);

class UInvenBook_LinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UInvenBook_LinkDataObject, ULinkDataObject, 0x0, T3Player)

public:
    virtual ~UInvenBook_LinkDataObject();   // slot 2: 0x10B12BE0

public:
};
T3_CHECK_SIZE(UInvenBook_LinkDataObject, 0x50);

class UT3Game : public UGameSubsystem
{
    DECLARE_CLASS(UT3Game, UGameSubsystem, 0x4, T3Player)

public:
    BYTE Pad34[0x188];
};
T3_CHECK_SIZE(UT3Game, 0x1BC);

class UT3GameEngine : public UGameEngine
{
    DECLARE_CLASS(UT3GameEngine, UGameEngine, 0xC, T3Player)

public:
    virtual ~UT3GameEngine();               // slot 2: 0x10B13650

public:
    BYTE thief3specificstuff[4];            // 0x17C
};
T3_CHECK_SIZE(UT3GameEngine, 0x180);

#endif
