// Fire/FireClasses.h: the Fire package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_FIRE_FIRECLASSES_H
#define T3_FIRE_FIRECLASSES_H

#include "Core/Core.h"
#include "Engine/EngineClasses.h"

class UTexture;

enum DMode
{
    DRAW_Normal,
    DRAW_Lathe,
    DRAW_Lathe_2,
    DRAW_Lathe_3,
    DRAW_Lathe_4
};

enum ESpark
{
    SPARK_Burn,
    SPARK_Sparkle,
    SPARK_Pulse,
    SPARK_Signal,
    SPARK_Blaze,
    SPARK_OzHasSpoken,
    SPARK_Cone,
    SPARK_BlazeRight,
    SPARK_BlazeLeft,
    SPARK_Cylinder,
    SPARK_Cylinder3D,
    SPARK_Lissajous,
    SPARK_Jugglers,
    SPARK_Emit,
    SPARK_Fountain,
    SPARK_Flocks,
    SPARK_Eels,
    SPARK_Organic,
    SPARK_WanderOrganic,
    SPARK_RandomCloud,
    SPARK_CustomCloud,
    SPARK_LocalCloud,
    SPARK_Stars,
    SPARK_LineLightning,
    SPARK_RampLightning,
    SPARK_SphereLightning,
    SPARK_Wheel,
    SPARK_Gametes,
    SPARK_Sprinkler
};

enum PanningType
{
    SLIDE_Linear,
    SLIDE_Circular,
    SLIDE_Gestation,
    SLIDE_WavyX,
    SLIDE_WavyY
};

enum TimingType
{
    TIME_FrameRateSync,
    TIME_RealTimeScroll
};

enum WDrop
{
    DROP_FixedDepth,
    DROP_PhaseSpot,
    DROP_ShallowSpot,
    DROP_HalfAmpl,
    DROP_RandomMover,
    DROP_FixedRandomSpot,
    DROP_WhirlyThing,
    DROP_BigWhirly,
    DROP_HorizontalLine,
    DROP_VerticalLine,
    DROP_DiagonalLine1,
    DROP_DiagonalLine2,
    DROP_HorizontalOsc,
    DROP_VerticalOsc,
    DROP_DiagonalOsc1,
    DROP_DiagonalOsc2,
    DROP_RainDrops,
    DROP_AreaClamp,
    DROP_LeakyTap,
    DROP_DrippyTap
};

struct FSpark
{
    BYTE Type;                              // 0x0  ESpark
    BYTE Heat;                              // 0x1
    BYTE X;                                 // 0x2
    BYTE Y;                                 // 0x3
    BYTE ByteA;                             // 0x4
    BYTE ByteB;                             // 0x5
    BYTE ByteC;                             // 0x6
    BYTE ByteD;                             // 0x7
};
T3_CHECK_SIZE(FSpark, 0x8);

struct FADrop
{
    BYTE Type;                              // 0x0  WDrop
    BYTE Depth;                             // 0x1
    BYTE X;                                 // 0x2
    BYTE Y;                                 // 0x3
    BYTE ByteA;                             // 0x4
    BYTE ByteB;                             // 0x5
    BYTE ByteC;                             // 0x6
    BYTE ByteD;                             // 0x7
};
T3_CHECK_SIZE(FADrop, 0x8);

class UFractalTexture : public UTexture
{
    DECLARE_CLASS(UFractalTexture, UTexture, 0x1, Fire)

public:
    INT UMask;                              // 0xDC
    INT VMask;                              // 0xE0
    INT LightOutput;                        // 0xE4
    INT SoundOutput;                        // 0xE8
    INT GlobalPhase;                        // 0xEC
    BYTE DrawPhase;                         // 0xF0
    BYTE AuxPhase;                          // 0xF1
};
T3_CHECK_SIZE(UFractalTexture, 0xF4);

class UFireTexture : public UFractalTexture
{
    DECLARE_CLASS(UFireTexture, UFractalTexture, 0x0, Fire)

public:
    BYTE SparkType;                         // 0xF4  ESpark
    BYTE RenderHeat;                        // 0xF5
    BITFIELD bRising:1;                     // 0xF8
    BYTE FX_Heat;                           // 0xFC
    BYTE FX_Size;                           // 0xFD
    BYTE FX_AuxSize;                        // 0xFE
    BYTE FX_Area;                           // 0xFF
    BYTE FX_Frequency;                      // 0x100
    BYTE FX_Phase;                          // 0x101
    BYTE FX_HorizSpeed;                     // 0x102
    BYTE FX_VertSpeed;                      // 0x103
    BYTE DrawMode;                          // 0x104  DMode
    INT SparksLimit;                        // 0x108
    INT NumSparks;                          // 0x10C
    TArray<FSpark> Sparks;                  // 0x110
    INT OldRenderHeat;                      // 0x11C
    BYTE RenderTable[1028];                 // 0x120
    BYTE StarStatus;                        // 0x524
    BYTE PenDownX;                          // 0x525
    BYTE PenDownY;                          // 0x526
};
T3_CHECK_SIZE(UFireTexture, 0x528);

class UWaterTexture : public UFractalTexture
{
    DECLARE_CLASS(UWaterTexture, UFractalTexture, 0x1, Fire)

public:
    BYTE DropType;                          // 0xF4  WDrop
    BYTE WaveAmp;                           // 0xF5
    BYTE FX_Frequency;                      // 0xF6
    BYTE FX_Phase;                          // 0xF7
    BYTE FX_Amplitude;                      // 0xF8
    BYTE FX_Speed;                          // 0xF9
    BYTE FX_Radius;                         // 0xFA
    BYTE FX_Size;                           // 0xFB
    BYTE FX_Depth;                          // 0xFC
    BYTE FX_Time;                           // 0xFD
    INT NumDrops;                           // 0x100
    FADrop Drops[256];                      // 0x104
    INT SourceFields;                       // 0x904
    BYTE RenderTable[1028];                 // 0x908
    BYTE WaterTable[1536];                  // 0xD0C
    BYTE WaterParity;                       // 0x130C
    INT OldWaveAmp;                         // 0x1310
};
T3_CHECK_SIZE(UWaterTexture, 0x1314);

class UFluidTexture : public UWaterTexture
{
    DECLARE_CLASS(UFluidTexture, UWaterTexture, 0x0, Fire)

public:
};
T3_CHECK_SIZE(UFluidTexture, 0x1314);

class UIceTexture : public UFractalTexture
{
    DECLARE_CLASS(UIceTexture, UFractalTexture, 0x0, Fire)

public:
    UTexture* GlassTexture;                 // 0xF4
    UTexture* SourceTexture;                // 0xF8
    BYTE PanningStyle;                      // 0xFC  PanningType
    BYTE TimeMethod;                        // 0xFD  TimingType
    BYTE HorizPanSpeed;                     // 0xFE
    BYTE VertPanSpeed;                      // 0xFF
    BYTE Frequency;                         // 0x100
    BYTE Amplitude;                         // 0x101
    BITFIELD MoveIce:1;                     // 0x104
    FLOAT MasterCount;                      // 0x108
    FLOAT UDisplace;                        // 0x10C
    FLOAT VDisplace;                        // 0x110
    FLOAT UPosition;                        // 0x114
    FLOAT VPosition;                        // 0x118
    FLOAT TickAccu;                         // 0x11C
    INT OldUDisplace;                       // 0x120
    INT OldVDisplace;                       // 0x124
    UTexture* OldGlassTex;                  // 0x128
    UTexture* OldSourceTex;                 // 0x12C
    INT LocalSource;                        // 0x130
    INT ForceRefresh;                       // 0x134
};
T3_CHECK_SIZE(UIceTexture, 0x138);

class UWaveTexture : public UWaterTexture
{
    DECLARE_CLASS(UWaveTexture, UWaterTexture, 0x0, Fire)

public:
    BYTE BumpMapLight;                      // 0x1314
    BYTE BumpMapAngle;                      // 0x1315
    BYTE PhongRange;                        // 0x1316
    BYTE PhongSize;                         // 0x1317
};
T3_CHECK_SIZE(UWaveTexture, 0x1318);

class UWetTexture : public UWaterTexture
{
    DECLARE_CLASS(UWetTexture, UWaterTexture, 0x0, Fire)

public:
    UTexture* SourceTexture;                // 0x1314
    UTexture* OldSourceTex;                 // 0x1318
    INT LocalSourceBitmap;                  // 0x131C
};
T3_CHECK_SIZE(UWetTexture, 0x1320);

#endif
