// GamePhysics/GamePhysicsClasses.h: the GamePhysics package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_GAMEPHYSICS_GAMEPHYSICSCLASSES_H
#define T3_GAMEPHYSICS_GAMEPHYSICSCLASSES_H

#include "Core/Core.h"
#include "Engine/EngineClasses.h"

class UGamePhysics : public UPhysicsSubsystem
{
    DECLARE_CLASS(UGamePhysics, UPhysicsSubsystem, 0x5, GamePhysics)

public:
    BYTE Pad38[0x74];
};
T3_CHECK_SIZE(UGamePhysics, 0xAC);

#endif
