// Core/CoreClasses.h: the Core package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_CORE_CORECLASSES_H
#define T3_CORE_CORECLASSES_H

#include "Core/Core.h"

enum ECamOrientation
{
    CAMORIENT_None,
    CAMORIENT_LookAtActor,
    CAMORIENT_FacePath,
    CAMORIENT_Interpolate
};

enum ESheerAxis
{
    SHEER_None,
    SHEER_XY,
    SHEER_XZ,
    SHEER_YX,
    SHEER_YZ,
    SHEER_ZX,
    SHEER_ZY
};

struct FScale
{
    FVector Scale;                          // 0x0
    FLOAT SheerRate;                        // 0xC
    BYTE SheerAxis;                         // 0x10  ESheerAxis
    BYTE Pad11[0x3];
};
T3_CHECK_SIZE(FScale, 0x14);

struct FColor
{
    BYTE B;                                 // 0x0
    BYTE G;                                 // 0x1
    BYTE R;                                 // 0x2
    BYTE A;                                 // 0x3
};
T3_CHECK_SIZE(FColor, 0x4);

struct FBox
{
    FVector Min;                            // 0x0
    FVector Max;                            // 0xC
    BYTE IsValid;                           // 0x18
    BYTE Pad19[0x3];
};
T3_CHECK_SIZE(FBox, 0x1C);

struct FRange
{
    FLOAT Min;                              // 0x0
    FLOAT Max;                              // 0x4
};
T3_CHECK_SIZE(FRange, 0x8);

struct FRangeVector
{
    FRange X;                               // 0x0
    FRange Y;                               // 0x8
    FRange Z;                               // 0x10
};
T3_CHECK_SIZE(FRangeVector, 0x18);

struct FPlane : public FVector
{
    FLOAT W;                                // 0xC
};
T3_CHECK_SIZE(FPlane, 0x10);

class USubsystem : public UObject
{
    DECLARE_CLASS(USubsystem, UObject, 0x9, Core)

public:
    INT ExecVtbl;                           // 0x2C
};
T3_CHECK_SIZE(USubsystem, 0x30);

class ULinkDataObject : public UObject
{
    DECLARE_CLASS(ULinkDataObject, UObject, 0x1, Core)

public:
    virtual void Unknown00();               // slot 0: 0x10B0F7F0
    virtual void Unknown20();               // slot 8: 0x10B0F5E0

public:
    INT m_LinkFlavor;                       // 0x2C
    INT m_pAssociatedLink;                  // 0x30
    FStringNoInit m_LinkComment;            // 0x34
    FStringNoInit m_name;                   // 0x40
    FName m_GroupName;                      // 0x4C
};
T3_CHECK_SIZE(ULinkDataObject, 0x50);

class UEnum : public UField
{
    DECLARE_CLASS(UEnum, UField, 0x0, Core)
    DECLARE_WITHIN(UStruct)

public:
    virtual ~UEnum();                       // slot 2: 0x10ADCAC0

public:
    BYTE Pad34[0xC];
};
T3_CHECK_SIZE(UEnum, 0x40);

class UBitfieldEnum : public UEnum
{
    DECLARE_CLASS(UBitfieldEnum, UEnum, 0x0, Core)

public:
    virtual ~UBitfieldEnum();               // slot 2: 0x10ADCB50
    virtual void Unknown20();               // slot 8: 0x10AD73F0

public:
};
T3_CHECK_SIZE(UBitfieldEnum, 0x40);

class UProperty : public UField
{
    DECLARE_CLASS(UProperty, UField, 0x1, Core)
    DECLARE_WITHIN(UField)

public:
    BYTE Pad34[0x2C];
};
T3_CHECK_SIZE(UProperty, 0x60);

class UIntProperty : public UProperty
{
    DECLARE_CLASS(UIntProperty, UProperty, 0x0, Core)

public:
    virtual ~UIntProperty();                // slot 2: 0x109768D0

public:
};
T3_CHECK_SIZE(UIntProperty, 0x60);

class UBitfieldProperty : public UIntProperty
{
    DECLARE_CLASS(UBitfieldProperty, UIntProperty, 0x0, Core)

public:
    virtual ~UBitfieldProperty();           // slot 2: 0x10AEE390
    virtual void Unknown20();               // slot 8: 0x10AEE150

public:
    BYTE Pad60[0x4];
};
T3_CHECK_SIZE(UBitfieldProperty, 0x64);

class UCommandlet : public UObject
{
    DECLARE_CLASS(UCommandlet, UObject, 0x29, Core)

public:
    virtual ~UCommandlet();                 // slot 2: 0x10976FA0

public:
    FStringNoInit HelpCmd;                  // 0x2C
    FStringNoInit HelpOneLiner;             // 0x38
    FStringNoInit HelpUsage;                // 0x44
    FStringNoInit HelpWebLink;              // 0x50
    FStringNoInit HelpParm[16];             // 0x5C
    FStringNoInit HelpDesc[16];             // 0x11C
    BITFIELD LogToStdout:1;                 // 0x1DC
    BITFIELD IsServer:1;
    BITFIELD IsClient:1;
    BITFIELD IsEditor:1;
    BITFIELD LazyLoad:1;
    BITFIELD ShowErrorCount:1;
    BITFIELD ShowBanner:1;
};
T3_CHECK_SIZE(UCommandlet, 0x1E0);

#endif
