// Core/CoreClasses.h: the Core package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_CORE_CORECLASSES_H
#define T3_CORE_CORECLASSES_H

#include "Core/Core.h"

enum ECamOrientation
{
    CAMORIENT_None,
    CAMORIENT_LookAtActor,
    CAMORIENT_FacePath,
    CAMORIENT_Interpolate
};

enum ESheerAxis
{
    SHEER_None,
    SHEER_XY,
    SHEER_XZ,
    SHEER_YX,
    SHEER_YZ,
    SHEER_ZX,
    SHEER_ZY
};

struct FScale
{
    FVector Scale;                          // 0x0
    FLOAT SheerRate;                        // 0xC
    BYTE SheerAxis;                         // 0x10  ESheerAxis
    BYTE Pad11[0x3];
};
T3_CHECK_SIZE(FScale, 0x14);

struct FColor
{
    BYTE B;                                 // 0x0
    BYTE G;                                 // 0x1
    BYTE R;                                 // 0x2
    BYTE A;                                 // 0x3
};
T3_CHECK_SIZE(FColor, 0x4);

struct FBox
{
    FVector Min;                            // 0x0
    FVector Max;                            // 0xC
    BYTE IsValid;                           // 0x18
    BYTE Pad19[0x3];
};
T3_CHECK_SIZE(FBox, 0x1C);

struct FRange
{
    FLOAT Min;                              // 0x0
    FLOAT Max;                              // 0x4
};
T3_CHECK_SIZE(FRange, 0x8);

struct FRangeVector
{
    FRange X;                               // 0x0
    FRange Y;                               // 0x8
    FRange Z;                               // 0x10
};
T3_CHECK_SIZE(FRangeVector, 0x18);

struct FPlane : public FVector
{
    FLOAT W;                                // 0xC
};
T3_CHECK_SIZE(FPlane, 0x10);

class ULinkDataObject : public UObject
{
public:
    INT m_LinkFlavor;                       // 0x2C
    INT m_pAssociatedLink;                  // 0x30
    FString m_LinkComment;                  // 0x34
    FString m_name;                         // 0x40
    FName m_GroupName;                      // 0x4C
};
T3_CHECK_SIZE(ULinkDataObject, 0x50);

class UCommandlet : public UObject
{
public:
    FString HelpCmd;                        // 0x2C
    FString HelpOneLiner;                   // 0x38
    FString HelpUsage;                      // 0x44
    FString HelpWebLink;                    // 0x50
    FString HelpParm[16];                   // 0x5C
    FString HelpDesc[16];                   // 0x11C
    BITFIELD LogToStdout:1;                 // 0x1DC
    BITFIELD IsServer:1;
    BITFIELD IsClient:1;
    BITFIELD IsEditor:1;
    BITFIELD LazyLoad:1;
    BITFIELD ShowErrorCount:1;
    BITFIELD ShowBanner:1;
};
T3_CHECK_SIZE(UCommandlet, 0x1E0);

class USubsystem : public UObject
{
public:
    INT ExecVtbl;                           // 0x2C
};
T3_CHECK_SIZE(USubsystem, 0x30);

#endif
