// AICore/AICoreClasses.h: the AICore package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_AICORE_AICORECLASSES_H
#define T3_AICORE_AICORECLASSES_H

#include "Core/Core.h"
#include "Engine/EngineClasses.h"

class AAIBehaviorModel;
class AAICombatModel;
class AAIFactionModel;
class AAIMovementModel;
class AAISensoryModel;

enum EEvidenceType
{
    EVIDENCE_GENERIC,
    EVIDENCE_VISUAL,
    EVIDENCE_SAW_PLAYER,
    EVIDENCE_SAW_ENEMY_NPC,
    EVIDENCE_SAW_ALERT_NPC,
    EVIDENCE_SAW_CHANGED_ACTOR,
    EVIDENCE_SAW_BODY,
    EVIDENCE_AUDIO,
    EVIDENCE_HEARD_ALARM,
    EVIDENCE_TACTILE,
    EVIDENCE_STIMULUS_DAMAGE,
    EVIDENCE_STIMULUS_GASSED,
    EVIDENCE_STIMULUS_SHOCKED,
    EVIDENCE_STIMULUS_BLINDED
};

enum EInferenceType
{
    INFERENCE_NOTHING,
    INFERENCE_INTRUDER,
    INFERENCE_VIOLENT,
    INFERENCE_KILLER,
    INFERENCE_THIEF,
    INFERENCE_PLAYER,
    INFERENCE_ANOMALY
};

enum EStateType
{
    STATE_NONE,
    STATE_IDLE,
    STATE_GREEN_ALERT,
    STATE_YELLOW_ALERT,
    STATE_RED_ALERT,
    STATE_SCRIPTED_CONVERSATION,
    STATE_DEAD,
    STATE_UNCONSCIOUS,
    STATE_FLEE,
    STATE_GUARD,
    STATE_RETURNING,
    STATE_PATROL,
    STATE_PATROL_LOOK,
    STATE_PATROL_FOLLOW,
    STATE_PATROL_FOLLOW_ABSOLUTE,
    STATE_PLAY_ANIM,
    STATE_EXIT_DANGER_ZONE,
    STATE_GASSED,
    STATE_SHOCKED,
    STATE_BLINDED,
    STATE_GREET_ACTOR,
    STATE_SEARCH,
    STATE_SEARCH_YELLOW,
    STATE_SEARCH_RED,
    STATE_SEARCH_BEHAVIOR,
    STATE_SEARCH_MOVE,
    STATE_SEARCH_TURN,
    STATE_SEARCH_TURN180,
    STATE_SEARCH_LOOK,
    STATE_SEARCH_AIM,
    STATE_FROB_ALARM,
    STATE_FATIGUED,
    STATE_PATHTEST,
    STATE_PLAYACTION,
    STATE_DORMANT,
    STATE_CONVERSATION_IDLE,
    STATE_WANDER,
    STATE_SIT,
    STATE_SLEEPING,
    STATE_APPROACH,
    STATE_FLEE_FROM_GRENADE,
    STATE_ONFIRE,
    STATE_BARK_SCRIPT,
    STATE_INFORM_RETURN,
    STATE_PLAYING_POSSUM,
    STATE_SLIP_AND_FALL,
    STATE_FETCH,
    STATE_FRUSTRATION,
    STATE_PLUMMETING,
    STATE_CHOKING,
    STATE_BEINGMUGGED,
    STATE_BASE_COMBAT,
    STATE_MELEE_COMBAT,
    STATE_RANGED_COMBAT,
    STATE_SELECT_POINT,
    STATE_TACTIC_AIM,
    STATE_TACTIC_UNAIM,
    STATE_TACTIC_FIRE,
    STATE_TACTIC_CROUCH,
    STATE_TACTIC_UNCROUCH,
    STATE_TACTIC_STEP,
    STATE_TACTIC_MOVE_TO_POINT,
    STATE_TACTIC_APPROACH_UNTIL_SEEN,
    STATE_TACTIC_BLESS_ALLY,
    STATE_EQUIP_WEAPON,
    STATE_HOLSTER_WEAPON,
    STATE_CHARGE_TARGET,
    STATE_MELEE_STRAFE_TARGET,
    STATE_MELEE_ATTACK_TARGET,
    STATE_THROW,
    STATE_OPTIONAL_MELEE_ANIM,
    STATE_DX2_INTERFACE,
    STATE_DX2_BOT_DOMINATED,
    STATE_DX2_STOP_FOR_PLAYER,
    STATE_DX2_IDLE_CAMERATURRET,
    STATE_DX2GREEN_ALERT_CAMERATURRET,
    STATE_DX2YELLOW_ALERT_CAMERATURRET,
    STATE_DX2RED_ALERT_CAMERATURRET,
    STATE_ZOMBIE_MUNCH_CORPSE,
    STATE_PREBACKSTAB
};

class AAIModel : public AMetaProperty
{
    DECLARE_CLASS(AAIModel, AMetaProperty, 0x0, AICore)

public:
    virtual ~AAIModel();                    // slot 2: 0x10962880

public:
};
T3_CHECK_SIZE(AAIModel, 0xC0);

class AAIBehaviorModel : public AAIModel
{
    DECLARE_CLASS(AAIBehaviorModel, AAIModel, 0x0, AICore)

public:
    virtual ~AAIBehaviorModel();            // slot 2: 0x10962920

public:
};
T3_CHECK_SIZE(AAIBehaviorModel, 0xC0);

class AAICombatModel : public AAIModel
{
    DECLARE_CLASS(AAICombatModel, AAIModel, 0x0, AICore)

public:
    virtual ~AAICombatModel();              // slot 2: 0x109629C0

public:
};
T3_CHECK_SIZE(AAICombatModel, 0xC0);

class AAIContextVolume : public AVolume
{
    DECLARE_CLASS(AAIContextVolume, AVolume, 0x0, AICore)

public:
    virtual ~AAIContextVolume();            // slot 2: 0x10B93430

public:
};
T3_CHECK_SIZE(AAIContextVolume, 0x148);

class AAIFactionModel : public AAIModel
{
    DECLARE_CLASS(AAIFactionModel, AAIModel, 0x0, AICore)

public:
    virtual ~AAIFactionModel();             // slot 2: 0x10962A60

public:
};
T3_CHECK_SIZE(AAIFactionModel, 0xC0);

class AAIMovementModel : public AAIModel
{
    DECLARE_CLASS(AAIMovementModel, AAIModel, 0x0, AICore)

public:
    virtual ~AAIMovementModel();            // slot 2: 0x10962B00

public:
    FLOAT CombatTurnSpeedMultiplier;        // 0xC0
    FLOAT TurnSpeed;                        // 0xC4
    FLOAT BendSpeed;                        // 0xC8
    FLOAT AimBeforeTurnAngleThreshold;      // 0xCC
    FLOAT TurnBlendInTime;                  // 0xD0
    FLOAT TurnBlendOutTime;                 // 0xD4
    FLOAT ConversationTurnSpeedMultiplier;  // 0xD8
    BITFIELD bKillBoneControllerOnMeleeAttack:1; // 0xDC
};
T3_CHECK_SIZE(AAIMovementModel, 0xE0);

class AAIPathPoint : public AMarker
{
    DECLARE_CLASS(AAIPathPoint, AMarker, 0x0, AICore)

public:
    virtual void Destroy();                 // slot 0: 0x10BBEF80
    virtual ~AAIPathPoint();                // slot 2: 0x10B93830
    virtual void Modify();                  // slot 6: 0x10BBF010
    virtual void PostLoad();                // slot 7: 0x10BBEF10
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x10BBEFD0

public:
    INT pad;                                // 0xC0
};
T3_CHECK_SIZE(AAIPathPoint, 0xC4);

class AAIPawn : public APawn
{
    DECLARE_CLASS(AAIPawn, APawn, 0x0, AICore)

public:
    virtual ~AAIPawn();                     // slot 2: 0x10B97680

public:
    BITFIELD DiagnosticsOn:1;               // 0x208
    UClass* OldSensoryModelClass_MaintainedForCompatibility; // 0x20C
    AAISensoryModel* SensoryModel;          // 0x210
    UClass* OldBehaviorModelClass_MaintainedForCompatibility; // 0x214
    AAIBehaviorModel* BehaviorModel;        // 0x218
    UClass* OldMovementModelClass_MaintainedForCompatibility; // 0x21C
    AAIMovementModel* MovementModel;        // 0x220
    UClass* OldCombatModelClass_MaintainedForCompatibility; // 0x224
    AAICombatModel* CombatModel;            // 0x228
    UClass* OldFactionModelClass_MaintainedForCompatibility; // 0x22C
    AAIFactionModel* FactionModel;          // 0x230
    FLOAT PickpocketingAngleThreshold;      // 0x234
};
T3_CHECK_SIZE(AAIPawn, 0x238);

class AAIPawnController : public AAIController
{
    DECLARE_CLASS(AAIPawnController, AAIController, 0x0, AICore)

public:
    virtual void Destroy();                 // slot 0: 0x10B9C520
    virtual ~AAIPawnController();           // slot 2: 0x10962790
    virtual void Serialize(FArchive& Ar);   // slot 8: 0x10B9BE00

public:
    BITFIELD initialized:1;                 // 0x114
    INT pad0;                               // 0x118
};
T3_CHECK_SIZE(AAIPawnController, 0x11C);

class AAISensoryModel : public AAIModel
{
    DECLARE_CLASS(AAISensoryModel, AAIModel, 0x0, AICore)

public:
    virtual ~AAISensoryModel();             // slot 2: 0x10962BA0

public:
};
T3_CHECK_SIZE(AAISensoryModel, 0xC0);

class AAITaggedVolume : public AVolume
{
    DECLARE_CLASS(AAITaggedVolume, AVolume, 0x0, AICore)

public:
    virtual ~AAITaggedVolume();             // slot 2: 0x10B934D0

public:
};
T3_CHECK_SIZE(AAITaggedVolume, 0x148);

class AAddAIPoint : public AAIPathPoint
{
    DECLARE_CLASS(AAddAIPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~AAddAIPoint();                 // slot 2: 0x10B938D0

public:
};
T3_CHECK_SIZE(AAddAIPoint, 0xC4);

class AChangeDirectionPoint : public AAIPathPoint
{
    DECLARE_CLASS(AChangeDirectionPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~AChangeDirectionPoint();       // slot 2: 0x10B93970

public:
};
T3_CHECK_SIZE(AChangeDirectionPoint, 0xC4);

class APatrolPoint : public AAIPathPoint
{
    DECLARE_CLASS(APatrolPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~APatrolPoint();                // slot 2: 0x10B93E00

public:
};
T3_CHECK_SIZE(APatrolPoint, 0xC4);

class ACityPopPoint : public APatrolPoint
{
    DECLARE_CLASS(ACityPopPoint, APatrolPoint, 0x0, AICore)

public:
    virtual ~ACityPopPoint();               // slot 2: 0x10B93E70
    virtual void PostLoad();                // slot 7: 0x10BC2F00

public:
};
T3_CHECK_SIZE(ACityPopPoint, 0xC4);

class ACitySectionPopulationInfo : public AInfo
{
    DECLARE_CLASS(ACitySectionPopulationInfo, AInfo, 0x0, AICore)

public:
    virtual ~ACitySectionPopulationInfo();  // slot 2: 0x10B940F0
    virtual void PostLoad();                // slot 7: 0x10BC2F20

public:
};
T3_CHECK_SIZE(ACitySectionPopulationInfo, 0xC0);

class AEnumEvidenceType : public AActor
{
    DECLARE_CLASS(AEnumEvidenceType, AActor, 0x0, AICore)

public:
    virtual ~AEnumEvidenceType();           // slot 2: 0x10B93610

public:
    BYTE DummyVariable;                     // 0xC0  EEvidenceType
};
T3_CHECK_SIZE(AEnumEvidenceType, 0xC4);

class AEnumInferenceType : public AActor
{
    DECLARE_CLASS(AEnumInferenceType, AActor, 0x0, AICore)

public:
    virtual ~AEnumInferenceType();          // slot 2: 0x10B936B0

public:
    BYTE DummyVariable;                     // 0xC0  EInferenceType
};
T3_CHECK_SIZE(AEnumInferenceType, 0xC4);

class AEnumStateType : public AActor
{
    DECLARE_CLASS(AEnumStateType, AActor, 0x0, AICore)

public:
    virtual ~AEnumStateType();              // slot 2: 0x10B93750

public:
    BYTE DummyVariable;                     // 0xC0  EStateType
};
T3_CHECK_SIZE(AEnumStateType, 0xC4);

class AFocusPoint : public AMarker
{
    DECLARE_CLASS(AFocusPoint, AMarker, 0x0, AICore)

public:
    virtual ~AFocusPoint();                 // slot 2: 0x10B93FB0

public:
};
T3_CHECK_SIZE(AFocusPoint, 0xC0);

class AFormationPoint : public AAIPathPoint
{
    DECLARE_CLASS(AFormationPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~AFormationPoint();             // slot 2: 0x10B93A10

public:
};
T3_CHECK_SIZE(AFormationPoint, 0xC4);

class AFormationPointAbsolute : public AAIPathPoint
{
    DECLARE_CLASS(AFormationPointAbsolute, AAIPathPoint, 0x0, AICore)

public:
    virtual ~AFormationPointAbsolute();     // slot 2: 0x10B93AB0

public:
};
T3_CHECK_SIZE(AFormationPointAbsolute, 0xC4);

class AHeadTurnPoint : public AAIPathPoint
{
    DECLARE_CLASS(AHeadTurnPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~AHeadTurnPoint();              // slot 2: 0x10B93B50

public:
};
T3_CHECK_SIZE(AHeadTurnPoint, 0xC4);

class ALookPoint : public AAIPathPoint
{
    DECLARE_CLASS(ALookPoint, AAIPathPoint, 0x0, AICore)

public:
    virtual ~ALookPoint();                  // slot 2: 0x10B93C20

public:
};
T3_CHECK_SIZE(ALookPoint, 0xC4);

class ANavMeshInsertionPoint : public AMarker
{
    DECLARE_CLASS(ANavMeshInsertionPoint, AMarker, 0x0, AICore)

public:
    virtual ~ANavMeshInsertionPoint();      // slot 2: 0x10B94050

public:
};
T3_CHECK_SIZE(ANavMeshInsertionPoint, 0xC0);

class ANavMeshSubtractionVolume : public AVolume
{
    DECLARE_CLASS(ANavMeshSubtractionVolume, AVolume, 0x0, AICore)

public:
    virtual ~ANavMeshSubtractionVolume();   // slot 2: 0x10B93570

public:
};
T3_CHECK_SIZE(ANavMeshSubtractionVolume, 0x148);

class APlayAnimPoint : public ALookPoint
{
    DECLARE_CLASS(APlayAnimPoint, ALookPoint, 0x0, AICore)

public:
    virtual ~APlayAnimPoint();              // slot 2: 0x10B93C90

public:
};
T3_CHECK_SIZE(APlayAnimPoint, 0xC4);

class APlayBarkPoint : public ALookPoint
{
    DECLARE_CLASS(APlayBarkPoint, ALookPoint, 0x0, AICore)

public:
    virtual ~APlayBarkPoint();              // slot 2: 0x10B93D30

public:
};
T3_CHECK_SIZE(APlayBarkPoint, 0xC4);

class AWanderPoint : public APatrolPoint
{
    DECLARE_CLASS(AWanderPoint, APatrolPoint, 0x0, AICore)

public:
    virtual ~AWanderPoint();                // slot 2: 0x10B93F10

public:
};
T3_CHECK_SIZE(AWanderPoint, 0xC4);

class UAI : public UAISubsystem
{
    DECLARE_CLASS(UAI, UAISubsystem, 0x4, AICore)

public:
    virtual ~UAI();                         // slot 2: 0x10BBE660

public:
};
T3_CHECK_SIZE(UAI, 0x34);

#endif
