// T3Game/T3GameClasses.h: the T3Game package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_T3GAME_T3GAMECLASSES_H
#define T3_T3GAME_T3GAMECLASSES_H

#include "Core/Core.h"
#include "Core/CoreClasses.h"
#include "Engine/EngineClasses.h"

enum eAICombatLevel
{
    kAICombat_Low,
    kAICombat_Normal,
    kAICombat_High,
    kAICombat_VeryHigh
};

enum eAIDensityLevel
{
    kAIDensity_Low,
    kAIDensity_Normal,
    kAIDensity_High
};

enum eAISenseLevel
{
    kAISense_Low,
    kAISense_Normal,
    kAISense_High,
    kAISense_VeryHigh
};

enum eDamageResistLevel
{
    kDamageResist_VeryLow,
    kDamageResist_Low,
    kDamageResist_Normal,
    kDamageResist_High,
    kDamageResist_VeryHigh
};

enum eDifficultyLevels
{
    kDifficulty_Easy,
    kDifficulty_Normal,
    kDifficulty_Hard,
    kDifficulty_Expert,
    kDifficulty_Custom
};

struct FDifficultyLevel
{
    INT LootPercent;                        // 0x0
    INT SpecialLoot;                        // 0x4
    INT MinBlackjack;                       // 0x8
    INT MaxBlackjack;                       // 0xC
    INT MinKill;                            // 0x10
    INT MaxKill;                            // 0x14
    BITFIELD DontBlackjackNonComb:1;        // 0x18
    BITFIELD DontKillNonComb:1;
    INT MaxDetected;                        // 0x1C
    INT MaxCorpsesFound;                    // 0x20
    BYTE AISenses;                          // 0x24  eAISenseLevel
    BYTE AICombat;                          // 0x25  eAICombatLevel
    BYTE AIDensity;                         // 0x26  eAIDensityLevel
    BYTE PlayerDamageResistance;            // 0x27  eDamageResistLevel
    INT TimeLimit;                          // 0x28
};
T3_CHECK_SIZE(FDifficultyLevel, 0x2C);

struct FLoadoutItem
{
    FStringNoInit ItemName;                 // 0x0
    INT Num;                                // 0xC
};
T3_CHECK_SIZE(FLoadoutItem, 0x10);

class ADifficultyInfo : public AInfo
{
    DECLARE_CLASS(ADifficultyInfo, AInfo, 0x0, T3Game)

public:
    virtual ~ADifficultyInfo();             // slot 2: 0x10AB3E20

public:
    FName LevelName;                        // 0xC0
    FDifficultyLevel EasyDiffSettings;      // 0xC4
    FDifficultyLevel NormalDiffSettings;    // 0xF0
    FDifficultyLevel HardDiffSettings;      // 0x11C
    FDifficultyLevel ExpertDiffSettings;    // 0x148
    BYTE CurrentDifficulty;                 // 0x174  eDifficultyLevels
    FDifficultyLevel CustomDiffSettings;    // 0x178
};
T3_CHECK_SIZE(ADifficultyInfo, 0x1A4);

class AEnterMissionInfo : public AInfo
{
    DECLARE_CLASS(AEnterMissionInfo, AInfo, 0x0, T3Game)

public:
    virtual ~AEnterMissionInfo();           // slot 2: 0x10AB58D0

public:
    BITFIELD EntryMapObjectFlag:1;          // 0xC0
    FStringNoInit VisibleObjectivesFileName; // 0xC4
    TArray<FLoadoutItem> DefaultInventory;  // 0xD0
    FStringNoInit BriefingFileName;         // 0xDC
    FStringNoInit BriefingVoiceOverSchemaName; // 0xE8
    BITFIELD AbortFlag:1;                   // 0xF4
    INT HandDrawnMap0;                      // 0xF8
    INT HandDrawnMap1;                      // 0xFC
    INT HandDrawnMap2;                      // 0x100
    INT HandDrawnMap3;                      // 0x104
    INT HandDrawnMap4;                      // 0x108
    FStringNoInit PostStartMissionBinkFileName; // 0x10C
};
T3_CHECK_SIZE(AEnterMissionInfo, 0x118);

class AExitMissionInfo : public AInfo
{
    DECLARE_CLASS(AExitMissionInfo, AInfo, 0x0, T3Game)

public:
    virtual ~AExitMissionInfo();            // slot 2: 0x10AB3F30

public:
    BITFIELD EntryMapObjectFlag:1;          // 0xC0
    FStringNoInit DestMapName;              // 0xC4
    FStringNoInit DestTeleportName;         // 0xD0
    FStringNoInit FirstVisitGlobalVar;      // 0xDC
    FStringNoInit PostContinueBinkFileName; // 0xE8
    FStringNoInit DebriefingVOSchemaName;   // 0xF4
};
T3_CHECK_SIZE(AExitMissionInfo, 0x100);

class ASpellProjectile : public AActor
{
    DECLARE_CLASS(ASpellProjectile, AActor, 0x800, T3Game)

public:
    virtual void Destroy();                 // slot 0: 0x10ABD7F0
    virtual ~ASpellProjectile();            // slot 2: 0x10AB4020

public:
    FRotator localRotationRate;             // 0xC0
    INT CollisionFilterInfo;                // 0xCC
    INT pad;                                // 0xD0
};
T3_CHECK_SIZE(ASpellProjectile, 0xD4);

class AWakeupCameraPoint : public AKeypoint
{
    DECLARE_CLASS(AWakeupCameraPoint, AKeypoint, 0x0, T3Game)

public:
    virtual ~AWakeupCameraPoint();          // slot 2: 0x10AB3D80

public:
    BITFIELD Start:1;                       // 0xC0
    FLOAT Seconds;                          // 0xC4
    INT UniqueId;                           // 0xC8
};
T3_CHECK_SIZE(AWakeupCameraPoint, 0xCC);

class UInventorySwitchLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(UInventorySwitchLinkDataObject, ULinkDataObject, 0x0, T3Game)

public:
    virtual ~UInventorySwitchLinkDataObject();// slot 2: 0x10AB4D80

public:
};
T3_CHECK_SIZE(UInventorySwitchLinkDataObject, 0x50);

class ULockLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(ULockLinkDataObject, ULinkDataObject, 0x0, T3Game)

public:
    virtual ~ULockLinkDataObject();         // slot 2: 0x10AB4E10

public:
};
T3_CHECK_SIZE(ULockLinkDataObject, 0x50);

class ULockTickLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(ULockTickLinkDataObject, ULinkDataObject, 0x0, T3Game)

public:
    virtual ~ULockTickLinkDataObject();     // slot 2: 0x10AB4EA0

public:
    FLOAT MidpointRotation;                 // 0x50
    FLOAT RotationFromCenter;               // 0x54
};
T3_CHECK_SIZE(ULockTickLinkDataObject, 0x58);

class URopeArrowSpawnLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(URopeArrowSpawnLinkDataObject, ULinkDataObject, 0x0, T3Game)

public:
    virtual ~URopeArrowSpawnLinkDataObject();// slot 2: 0x10AB4F60

public:
    FLOAT RopeLength;                       // 0x50
    FStringNoInit UnfurlAnimName;           // 0x54
};
T3_CHECK_SIZE(URopeArrowSpawnLinkDataObject, 0x60);

class USpawnPoolLinkDataObject : public ULinkDataObject
{
    DECLARE_CLASS(USpawnPoolLinkDataObject, ULinkDataObject, 0x0, T3Game)

public:
    virtual ~USpawnPoolLinkDataObject();    // slot 2: 0x10AB5000

public:
};
T3_CHECK_SIZE(USpawnPoolLinkDataObject, 0x50);

class UT3GameRegistrar : public UTriggerRegistrar
{
    DECLARE_CLASS(UT3GameRegistrar, UTriggerRegistrar, 0x4, T3Game)

public:
};
T3_CHECK_SIZE(UT3GameRegistrar, 0x2C);

#endif
