#!/usr/bin/env python3
"""PreToolUse guard for matching workers.

Two ways in:
  - .claude/settings.json runs it on every tool call of the session, the
    lead's included, with `--agent-types t3-matcher`: it then checks only
    calls whose hook input names one of those sub-agent types (`agent_type`,
    present when a sub-agent makes the call) and lets the lead's through.
    A hook in the agent definition's own frontmatter does not run for
    sub-agents started with the Agent tool (Claude Code 2.1.287); the
    project settings' hook does, with `agent_type` set.
  - tools/agent/guard-settings.json runs it for the headless workers of
    wave.py, each a session of its own: without the option every call is
    checked.

Workers write only their scratch files, build/scratch/ in their own checkout.
The rest is the lead's: config/, configure.py, objdiff.json, orig/, src/,
include/, build/ (split objects, claims, accepted records), the tools and
agent files, and anything outside the checkout. Bash commands that discard
work or skip checks (git stash/reset/checkout ./clean/..., --no-verify,
recursive rm), inline interpreters, lead-only tool options, and writes to
protected paths through redirections, tee, sed -i, cp, mv, rm, touch, dd or
ln are refused.

Claude Code passes the tool call as JSON on stdin; exit status 2 with a
reason on stderr blocks it. An error inside the guard also blocks: it fails
closed.
"""

import json
import os
import re
import shlex
import sys
from pathlib import Path
from typing import List, Optional

SCRATCH = "build/scratch/"
PROTECTED = [
    ("config/", "config/ (symbols.txt, splits.txt) is the lead's"),
    ("configure.py", "configure.py is the lead's"),
    ("objdiff.json", "objdiff.json is generated by configure.py"),
    ("build.ninja", "build.ninja is generated by configure.py"),
    ("orig/", "orig/ holds the game's files"),
    ("src/", "src/ is written by the lead's integrate.py; record matches with accept.py"),
    ("include/", "include/ headers are the lead's; ask for changes in your summary's needs"),
    ("build/", "build/ holds the split objects and the shared state; write scratch files under build/scratch/"),
    ("tools/", "the tools are the lead's"),
    (".claude/", "agent definitions and the cheat sheet are the lead's; propose entries in your summary"),
]
DENY_BASH = [
    (r"\bgit\s+(stash|reset|clean|restore|rebase|push|commit|merge|cherry-pick|revert|filter-branch|update-ref|gc|"
     r"prune)\b", "git commands that change history or discard work are the lead's"),
    (r"\bgit\s+checkout\s+(-f\b|--force\b|(--\s+)?\.(\s|$)|--\s)", "git checkout that discards changes"),
    (r"\bgit\s+(worktree|branch\s+-[dD])\b", "git worktrees and branches are managed by wave.py"),
    (r"--no-verify\b", "--no-verify skips checks"),
    (r"\brm\s+(-\w*[rR]\w*|--recursive)\b", "recursive rm"),
    (r"\b(python[\d.]*|py|perl|ruby|node|bash|sh|pwsh|powershell)(\.exe)?\s+(-\w*[ce]\w*\b|-\s|-$|<<|<)",
     "inline scripts (run the tools in tools/agent/ instead)"),
    (r"\b(integrate|wave|sweep|fixnames|retry|dtors|rename)\.py\b",
     "integrate.py, wave.py, sweep.py, fixnames.py, retry.py, dtors.py and rename.py are the lead's"),
    (r"\bnext\.py\s+(requeue|release\s+.*--all)", "requeue and release --all are the lead's"),
    (r"\bclusters\.py\s+stamp\b", "stamping families is the lead's"),
    (r"\bcontext\.py\s+fill-ghidra\b", "filling the Ghidra cache is the lead's"),
    (r"\s--(cap|replace|patience|include-siblings)\b",
     "--cap, --patience, --replace and --include-siblings are the lead's"),
    (r"\bT3_AGENT_(MAIN|CONFIG|OBJ|STATE|EXE|SRC)\s*=", "the T3_AGENT_* paths are fixed for workers"),
]
WRITERS = {"tee", "touch", "truncate", "rm", "rmdir", "cp", "mv", "ln", "install", "mkdir", "chmod", "chown",
           "unlink", "rsync"}


def deny(reason: str) -> None:
    sys.stderr.write(f"Blocked by the matching guard: {reason}\n")
    sys.exit(2)


def check_path(raw: str, cwd: Path, project: Path) -> Optional[str]:
    """Why a worker may not write `raw`, or None."""
    if raw in ("/dev/null", "/dev/stdout", "/dev/stderr", "nul", "NUL"):
        return None
    path = Path(os.path.expanduser(raw))
    path = (path if path.is_absolute() else cwd / path).resolve()
    try:
        rel = path.relative_to(project).as_posix()
    except ValueError:
        return f"{raw} is outside your checkout ({project})"
    if (rel + "/").startswith(SCRATCH):
        return None
    for prefix, why in PROTECTED:
        if rel == prefix.rstrip("/") or rel.startswith(prefix):
            return f"{raw}: {why}"
    return f"{raw}: workers write only under {SCRATCH}"


def bash_targets(command: str) -> List[str]:
    """Paths a shell command may write: redirections, and the operands of writing commands."""
    try:
        lexer = shlex.shlex(command, posix=True, punctuation_chars=";&|<>")
        lexer.whitespace_split = True
        tokens = list(lexer)
    except ValueError:
        return ["<unparsable command>"]
    targets, segment = [], []
    for tok in tokens + [";"]:
        if tok and set(tok) <= set(";&|"):
            targets += _segment_targets(segment)
            segment = []
        else:
            segment.append(tok)
    return targets


def _segment_targets(seg: List[str]) -> List[str]:
    out, words = [], []
    i = 0
    while i < len(seg):
        tok = seg[i]
        if tok.isdigit() and i + 1 < len(seg) and seg[i + 1][:1] in "<>":
            i += 1  # the file descriptor of 2>file
            continue
        if tok in (">&", "<&", "&>&"):
            i += 2  # 2>&1: a descriptor, not a file
            continue
        if tok in (">", ">>", ">|", "&>", "&>>"):
            if i + 1 < len(seg) and not seg[i + 1].startswith("&"):
                out.append(seg[i + 1])
            i += 2
            continue
        if tok in ("<", "<<", "<<<"):
            i += 2
            continue
        words.append(tok)
        i += 1
    while words and re.fullmatch(r"\w+=.*", words[0]):
        words.pop(0)  # leading VAR=value assignments
    if not words:
        return out
    cmd = os.path.basename(words[0]).lower().replace(".exe", "")
    args = [w for w in words[1:] if not w.startswith("-")]
    if cmd in WRITERS:
        out += args[-1:] if cmd in ("cp", "mv", "ln", "install", "rsync") else args
    elif cmd == "sed" and any(w.startswith("-i") or w == "--in-place" for w in words[1:]):
        out += args[1:]
    elif cmd == "dd":
        out += [w[3:] for w in words[1:] if w.startswith("of=")]
    elif cmd in ("git", "curl", "wget") and ("-o" in words or "--output" in words or "-O" in words):
        out += [words[words.index(o) + 1] for o in ("-o", "--output", "-O") if o in words[:-1]]
    return out


def main() -> None:
    event = json.load(sys.stdin)
    if "--agent-types" in sys.argv[1:]:
        i = sys.argv.index("--agent-types")
        types = {t for t in (sys.argv[i + 1] if i + 1 < len(sys.argv) else "").split(",") if t}
        if event.get("agent_type") not in types:
            sys.exit(0)  # the lead, or another kind of sub-agent
    tool = event.get("tool_name", "")
    data = event.get("tool_input", {}) or {}
    cwd = Path(event.get("cwd") or os.getcwd()).resolve()
    project = Path(os.environ.get("CLAUDE_PROJECT_DIR") or cwd).resolve()
    if tool in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
        path = data.get("file_path") or data.get("notebook_path") or ""
        why = check_path(path, cwd, project)
        if why:
            deny(why)
    elif tool == "Bash":
        command = data.get("command", "")
        for pattern, why in DENY_BASH:
            if re.search(pattern, command):
                deny(why)
        for target in bash_targets(command):
            why = check_path(target, cwd, project)
            if why:
                deny(why)
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:  # fail closed
        deny(f"guard error: {e}")
