// T3AI/T3AIClasses.h: the T3AI package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_T3AI_T3AICLASSES_H
#define T3_T3AI_T3AICLASSES_H

#include "Core/Core.h"
#include "AICore/AICoreClasses.h"

class AT3AIPawnController : public AAIPawnController
{
public:
};
T3_CHECK_SIZE(AT3AIPawnController, 0x11C);

class AT3BehaviorModel : public AAIBehaviorModel
{
public:
};
T3_CHECK_SIZE(AT3BehaviorModel, 0xC0);

class AT3CombatModel : public AAICombatModel
{
public:
};
T3_CHECK_SIZE(AT3CombatModel, 0xC0);

class AT3FactionModel : public AAIFactionModel
{
public:
};
T3_CHECK_SIZE(AT3FactionModel, 0xC0);

class AT3MovementModel : public AAIMovementModel
{
public:
};
T3_CHECK_SIZE(AT3MovementModel, 0xE0);

class AT3SensoryModel : public AAISensoryModel
{
public:
};
T3_CHECK_SIZE(AT3SensoryModel, 0xC0);

#endif
