// T3GamePhysics/T3GamePhysicsClasses.h: the T3GamePhysics package's native classes, as the game's scripts declare
// them (names, types, offsets) and T3Main.exe sizes them. Generated by
// tools/assets/t3classes.py: do not edit.
#ifndef T3_T3GAMEPHYSICS_T3GAMEPHYSICSCLASSES_H
#define T3_T3GAMEPHYSICS_T3GAMEPHYSICSCLASSES_H

#include "Core/Core.h"
#include "GamePhysics/GamePhysicsClasses.h"

class UT3GamePhysics : public UGamePhysics
{
    DECLARE_CLASS(UT3GamePhysics, UGamePhysics, 0x4, T3GamePhysics)

public:
};
T3_CHECK_SIZE(UT3GamePhysics, 0xAC);

#endif
