"""Whose code each address range is: config/<version>/categories.txt.

tools/classify.py writes the file from T3Main.exe (see there for the evidence);
configure.py reads it to give each unit its progress category and to keep auto
units from spanning two categories. One range per line, half-open, in the style
of splits.txt:

    game    start:0x10901000 end:0x10964A80
"""

import bisect
import re
from pathlib import Path
from typing import List, Sequence, Tuple

GAME, ENGINE, LIBS, UNKNOWN = "game", "engine", "libs", "unknown"
CATEGORIES = (GAME, ENGINE, LIBS, UNKNOWN)

Range = Tuple[int, int, str]
_LINE = re.compile(r"^(?P<category>\w+)\s+start:0x(?P<start>[0-9A-Fa-f]+)\s+end:0x(?P<end>[0-9A-Fa-f]+)$")
HEADER = """\
# Whose code each address range is. Generated by tools/classify.py from T3Main.exe; do not edit.
#   game     Ion Storm's code: the decompilation covers it
#   engine   Epic's Unreal Engine 2: not decompiled, the game compiles against it
#   libs     third-party libraries: not decompiled
#   unknown  no evidence yet
# Half-open ranges over .text, outside .text$x (EH funclets go with their parent function).
"""


def load(path: Path) -> List[Range]:
    """The ranges of a categories.txt, sorted; an empty list if there is none."""
    path = Path(path)
    if not path.is_file():
        return []
    out: List[Range] = []
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        m = _LINE.match(line)
        if not m or m.group("category") not in CATEGORIES:
            raise ValueError(f"{path}:{lineno}: expected '<{'|'.join(CATEGORIES)}> start:0x.. end:0x..'")
        start, end = int(m.group("start"), 16), int(m.group("end"), 16)
        if end <= start:
            raise ValueError(f"{path}:{lineno}: empty or reversed range")
        out.append((start, end, m.group("category")))
    out.sort()
    for a, b in zip(out, out[1:]):
        if b[0] < a[1]:
            raise ValueError(f"{path}: ranges overlap at 0x{b[0]:08X}")
    return out


def save(path: Path, ranges: Sequence[Range]) -> None:
    lines = [f"{c:<8}start:0x{a:08X} end:0x{b:08X}" for a, b, c in ranges]
    Path(path).write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")


class Index:
    """Category lookups by address."""

    def __init__(self, ranges: Sequence[Range]):
        self.ranges = list(ranges)
        self.starts = [r[0] for r in self.ranges]

    def at(self, address: int) -> str:
        """The category of an address, or "" outside every range (.text$x, data)."""
        i = bisect.bisect_right(self.starts, address) - 1
        return self.ranges[i][2] if i >= 0 and address < self.ranges[i][1] else ""

    def covering(self, start: int, end: int) -> List[str]:
        """The categories [start, end) overlaps, in address order."""
        i = max(bisect.bisect_right(self.starts, start) - 1, 0)
        out: List[str] = []
        while i < len(self.ranges) and self.ranges[i][0] < end:
            if self.ranges[i][1] > start and self.ranges[i][2] not in out[-1:]:
                out.append(self.ranges[i][2])
            i += 1
        return out

    def boundaries(self) -> List[int]:
        """Every address where the category changes."""
        return sorted({a for a, _, _ in self.ranges} | {b for _, b, _ in self.ranges})
